MWPW-129400 update consumer config and baseURL structure
adobecom/nala pull request #101
Opened 2023-04-09 02:42 UTC by skumar09

[MWPW-129400](https://jira.corp.adobe.com/browse/MWPW-129400) : Enhance Nala framework playwright.config.js projects and baseURL structure.

This PR fixes the following current issues:

1. Test scripts are executed as per the value(s) specified in the `env` param in `.spec.js files`.  
    Ex: In the below example spec, test script execution is repeated against each tag and each environment. i.e. in a single GitHub run, the below script is run four times, which is not required. Also, the user should be able to run the test against specified tags in a given environment.
```
  features: [
    {
      tcid: '1',
      name: '@Carousel(container)',
      path: '/drafts/nala/blocks/carousel/lightbox',
      tags: '@carousel @carousel-container @smoke @regression @milo,',
      envs: '@milo-live @milo-prod',
    },]

```
2. Test execution on multiple environments or URLs is tightly coupled with `.spec.js files`.
    - Ideally, the user should be able to run scripts against any given environment, (if the feature is available in that environment)
    - User should be able to instruct from GitHub (or outside the `.spec.js `or test cases files ) to run the test scripts on a specified environment.    
3. Consumer does not have separate config.js files to maintain their own sub-projects and URLs for their run.

**Updates about PR:**
1. 
![image](https://user-images.githubusercontent.com/22153717/230750823-1de07d55-8949-42db-803f-11b5e0a4e316.png)
2. 
![image](https://user-images.githubusercontent.com/22153717/230751204-3de33beb-8236-49f4-b52b-d6ece6860edf.png)
3.
![image](https://user-images.githubusercontent.com/22153717/230751303-f3d81737-cf8d-4c88-bff1-67abf80c2e24.png)

2023-04-10 17:40 UTC, JackySun9 reviewed
Can we get dynamic config.js per user input, then not hard code into each config.js

2023-04-10 18:38 UTC, skumar09 commented
> Can we get dynamic config.js per user input, then not hard code into each config.js

@JackySun9 
- config.js is not hard coded, each consuming application can have its own config.js and its own setup & and sub-projects (i.e. running on tests on different env like a stage, prod, preview, live etc and different platform/browser combinations and use `use: {} param ` for different re-usable parameters. )
- Also will schedule a call to walk through the above things.

2023-04-10 23:23 UTC, amauch-adobe requested changes

2023-04-10 23:23 UTC, amauch-adobe commented on configs/bacom.config.js
> +    : [['html', { outputFolder: 'test-html-results' }], ['../utils/reporters/json-reporter.js']],
having the json-reporter for local executions causes the output in the IDE terminal to be a one-liner saying test results have been sent to nala.json. Microsoft has created a Playwright extension for VSCode that allows you to run test executions via the IDE rather than having to run it through a command prompt or terminal window outside of the IDE. Where you already have the HTML report I don't think we need to have the json-reporter added for local executions since it was created solely for the use of the Nala Dashboard application. When the json-reporter is removed the VSCode extension for Playwright shows exceptions track traces, which test is running on what browser, and its overall result.

I think it should be removed and be only used for github.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/blog.config.js
> +    : [['html', { outputFolder: 'test-html-results' }], ['../utils/reporters/json-reporter.js']],
having the json-reporter for local executions causes the output in the IDE terminal to be a one-liner saying test results have been sent to nala.json. Microsoft has created a Playwright extension for VSCode that allows you to run test executions via the IDE rather than having to run it through a command prompt or terminal window outside of the IDE. Where you already have the HTML report I don't think we need to have the json-reporter added for local executions since it was created solely for the use of the Nala Dashboard application. When the json-reporter is removed the VSCode extension for Playwright shows exceptions track traces, which test is running on what browser, and its overall result.

I think it should be removed and be only used for github.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/dc.config.js
> +    : [['html', { outputFolder: 'test-html-results' }], ['../utils/reporters/json-reporter.js']],
having the json-reporter for local executions causes the output in the IDE terminal to be a one-liner saying test results have been sent to nala.json. Microsoft has created a Playwright extension for VSCode that allows you to run test executions via the IDE rather than having to run it through a command prompt or terminal window outside of the IDE. Where you already have the HTML report I don't think we need to have the json-reporter added for local executions since it was created solely for the use of the Nala Dashboard application. When the json-reporter is removed the VSCode extension for Playwright shows exceptions track traces, which test is running on what browser, and its overall result.

I think it should be removed and be only used for github.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/feds.config.js
> +    : [['html', { outputFolder: 'test-html-results' }], ['../utils/reporters/json-reporter.js']],
having the json-reporter for local executions causes the output in the IDE terminal to be a one-liner saying test results have been sent to nala.json. Microsoft has created a Playwright extension for VSCode that allows you to run test executions via the IDE rather than having to run it through a command prompt or terminal window outside of the IDE. Where you already have the HTML report I don't think we need to have the json-reporter added for local executions since it was created solely for the use of the Nala Dashboard application. When the json-reporter is removed the VSCode extension for Playwright shows exceptions track traces, which test is running on what browser, and its overall result.

I think it should be removed and be only used for github.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/milo.config.js
> +    : [['html', { outputFolder: 'test-html-results' }], ['../utils/reporters/json-reporter.js']],
having the json-reporter for local executions causes the output in the IDE terminal to be a one-liner saying test results have been sent to nala.json. Microsoft has created a Playwright extension for VSCode that allows you to run test executions via the IDE rather than having to run it through a command prompt or terminal window outside of the IDE. Where you already have the HTML report I don't think we need to have the json-reporter added for local executions since it was created solely for the use of the Nala Dashboard application. When the json-reporter is removed the VSCode extension for Playwright shows exceptions track traces, which test is running on what browser, and its overall result.

I think it should be removed and be only used for github.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/dc.config.js
I know there is a config for acom that includes the environment adobe prod and adobe stage, but it might confuse the DC team to have the two configs.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/dc.config.js
I know there is a config for acom that includes the environment adobe prod and adobe stage, but it might confuse the DC team to have the two configs.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/feds.config.js
> +// require('dotenv').config();
probably should remove this commented code out so it doesn't remain in all of the configs, if we are going to use the third-party library then let's keep it, if not. No reason, to leave it there commented out.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/milo.config.js
> +// require('dotenv').config();
probably should remove this commented code out so it doesn't remain in all of the configs, if we are going to use the third-party library then let's keep it, if not. No reason, to leave it there commented out.

2023-04-10 23:23 UTC, amauch-adobe commented on features/milo/carousel.block.spec.js
> +      tags: '@carousel @carousel-container @smoke @t1 @regression @milo,',
just a quick question how are we going to keep track of the test numbers as tags, I just worry we will have developers forget which number it should be, and how it coincides with different implementations, integrations, etc.  Just trying to get ahead of it before it becomes a problem.

2023-04-10 23:23 UTC, amauch-adobe commented on configs/dc.config.js
I know there is a config for acom that includes the environment adobe prod and adobe stage, but it might confuse the DC team to have the two configs.

2023-04-10 23:23 UTC, amauch-adobe commented on run.sh
My biggest concern here is complexity.  How well do we think this will be incorporated correctly with engineers when they create PRs since they are generally the ones that add (or don't add for that matter :) ) labels to their PRs.  With how this implementation is set up a Milo engineer will need to add run-on-milo-live, run-on-milo-prod... and any other run-on-<environment> for a specific feature that they have newly developed, updated, etc. We already are having problems trying to get the engineers to add the 'run-nala' label, and if they understand how the test tag labels work, those as well.  Are we planning on doing it for them and watching out for every PR that gets issued to Milo?  One of Chris Millar's requests with Nala was to keep it simple and something that all engineers, not just QEs would want to use. 

Also, with how the current github actions workflow is set up you would also need to add the 'run-nala' label and then 'run-on-<application env>' label.  

My other concern is this only allows the execution of tests against one environment/project config, how do we run and execute test tags that are to run against multiple environments, for example, I create a PR to update the columns block and I need the Nala tests to run against Milo Live, and Bacom Live, and Blog live.  How would that work with the project/config command?

@skumar09 please understand these are concerns and questions in my mind as I looked over the PR, I'm not writing it in a tone of anger or negativity.  I just want to understand the full plan here and ensure we are keeping to stakeholder requests (granted things could have changed where I'm no longer on the Milo team and you could have gotten a different direction presented to you than I was at the time).

2023-04-11 19:15 UTC, JackySun9 approved these changes

2023-04-12 20:44 UTC, JFernandezAdobe commented on configs/acom.config.js
> +      name: 'adobe-prodchrome',
Is this supposed to be 'adobe-prod-chrome' with the dash before chrome?

2023-04-12 21:15 UTC, JFernandezAdobe approved these changes
LGTM

2023-04-14 19:18 UTC, amauch-adobe approved these changes
Approved.  Thanks for going through this with me today.

2023-04-14 20:27 UTC, merged