[MWPW-129263] Update consent checks to match new PO logic
adobecom/nala pull request #103
Opened 2023-04-11 14:11 UTC by chadsunvice

2023-04-14 20:39 UTC, amauch-adobe requested changes
Just a small nitpick on two comments in one file and path changes.  Other than that everything looks great!

2023-04-14 20:39 UTC, amauch-adobe commented on pages/feds.consent.page.js
> +    // Wait for the out-out modal to be displayed:
I believe this is supposed to be "opt-out" instead of "out-out".

2023-04-14 20:39 UTC, amauch-adobe commented on pages/feds.consent.page.js
> +    // Close the out-out modal & assert result:
same case here.  I believe this is supposed to be "opt-out" instead of "out-out".

2023-04-14 20:39 UTC, amauch-adobe commented on tests/feds/consent.test.js
> +import { FedsConsent } from '../../pages/feds.consent.page';
per change requirements with @skumar09 PR #101 we will be moving all page.js files to be under /selectors/feds/ directory to be consistent across the board for all teams.  Please adjust all .test.js files using imports from /pages/... to be updated to /selectors/feds/... instead.

2023-04-14 20:39 UTC, amauch-adobe commented on tests/feds/consent.test.js
> +import { FedsConsent } from '../../pages/feds.consent.page';
I've already created and merged a PR to move your page files to the /selectors/feds/ directory.  So after updating your PR to be in sync with "main", you will just need to update your PR with the path changes.

2023-04-17 20:03 UTC, amauch-adobe approved these changes
Approved.  Thanks.

2023-04-17 22:09 UTC, JackySun9 approved these changes

2023-04-17 22:10 UTC, merged