Adding stats block test.
adobecom/nala pull request #106
Opened 2023-04-17 23:01 UTC by Dli3

Adding tests for the stats block on bacom.

Ticket: https://jira.corp.adobe.com/browse/MWPW-126249

2023-04-17 23:34 UTC, JackySun9 approved these changes

2023-04-18 00:48 UTC, amauch-adobe requested changes
Great job on POM usage and test step methods, see my comments inline.

2023-04-18 00:48 UTC, amauch-adobe commented on selectors/bacom/stats.page.js
> +    this.statsLink = page.locator('.stat > div > p > strong > a');
Just a quick question does the final locator of the links have a unique class name or id?  If they do it is recommended by Playwright to use those before using CSS paths.  If not, no worries.

2023-04-18 00:48 UTC, amauch-adobe commented on tests/bacom/stat.test.js
> +      await page.goto(testPage);
I would just add these two lines (15-16) into the test step method since you do these same calls again just before starting the next test step, then it is all tied to the test step.

2023-04-18 00:48 UTC, amauch-adobe commented on tests/bacom/stat.test.js
> +      await page.goto(testPage);
Same here as above.  I would just add these two lines (23-24) into the test step method then it is all tied to the test step.

2023-04-18 16:08 UTC, Dli3 commented on selectors/bacom/stats.page.js
> +    this.statsLink = page.locator('.stat > div > p > strong > a');
They don't. But thanks for bringing that up!

2023-04-18 16:15 UTC, Dli3 commented on tests/bacom/stat.test.js
> +      await page.goto(testPage);
Great suggestion. The lines have been moved. Thanks!

2023-04-18 16:15 UTC, Dli3 commented on tests/bacom/stat.test.js
> +      await page.goto(testPage);
Great suggestion. The lines have been moved. Thanks!

2023-04-18 18:03 UTC, skumar09 approved these changes

2023-04-18 21:18 UTC, amauch-adobe approved these changes
Approved.

2023-04-19 01:58 UTC, skumar09 commented
@Dli3: Earlier it seems an issue with the labels, I have updated the labels, and the tests are passed, please review once before merging.

2023-04-19 18:24 UTC, merged