Add analytics test for uar
adobecom/nala pull request #123
Opened 2023-05-19 17:41 UTC by JackySun9

https://jira.corp.adobe.com/browse/MWPW-126153
1. add utils for analytics test
2. add uar as sample for analytics test
3. this is only working for firefox

2023-05-19 19:18 UTC, skumar09 commented on tests/uar/quiz.analytics.test.js
> +});
@JackySun9 : trying to understand the context for `capturing network logs`, are we using it for some validations?

2023-05-19 19:18 UTC, skumar09 commented on tests/uar/quiz.analytics.test.js
> +  test.setTimeout(3 * 60 * 1000);
- you may want to move `test.setTimeout()` inside test() function/method
- if you need 3 times of default timeout, you may want to use `test.slow()` as below or you can use `test.beforeEach()` to setTimeout
```
- test('slow test', async ({ page }) => {
  test.slow(); 
  // ...
});
```

2023-05-19 19:18 UTC, skumar09 commented on libs/webutil.js
> +        // eslint-disable-next-line max-len, no-underscore-dangle
- You want to split the code line, to avoid adding // eslint-disable-next-line max-len
- I know we have this on many other tests, and i am trying to format them..

2023-05-19 19:18 UTC, skumar09 commented on features/uar/quiz.analytics.spec.js
> +      tags: '@quiz-analytics-single-template @quiz-analytics',
- In tags you may want to include the project name, something like `cc or uar` kind.

2023-05-22 17:44 UTC, JackySun9 commented on tests/uar/quiz.analytics.test.js
> +});
Currently I just catch the real logs and put them into an array, I am thinking where to put the expected data and add the validation part

2023-05-22 17:45 UTC, JackySun9 commented on libs/webutil.js
> +        // eslint-disable-next-line max-len, no-underscore-dangle
how to do this?

2023-05-22 17:45 UTC, JackySun9 commented on features/uar/quiz.analytics.spec.js
> +      tags: '@quiz-analytics-single-template @quiz-analytics',
sure, will do

2023-05-22 20:16 UTC, amauch-adobe requested changes
Approved, just address @skumar09's comments

2023-05-24 14:08 UTC, chadsunvice approved these changes
Looks good Jacky! 👍

2023-05-24 14:08 UTC, chadsunvice commented on features/uar/quiz.spec.js
> +      tags: '@uar-quiz-single-template @uar-quiz-static',
I suggest we use some team-specific tags for each test as to have a way to filter checks/run regressions from team-perspective too. (eg: `tags: '@cc @uar-quiz-single-template @uar-quiz-static',`)

2023-05-24 14:08 UTC, chadsunvice commented on features/uar/quiz.spec.js
> +      tags: '@uar-quiz-double-template @uar-quiz-static',
I suggest we use some team-specific tags for each test as to have a way to filter checks/run regressions from team-perspective too. (eg: `tags: '@cc @uar-quiz-single-template @uar-quiz-static',`)

Same goes for all other test tag lines.

2023-05-24 23:04 UTC, skumar09 requested changes

2023-05-24 23:04 UTC, skumar09 commented on libs/webutil.js
> +    await this.page.close();
- do we need `page.close()` to disable network logging
- we may have a scenario where we just want to capture network logs for a single navigation/click or single test step.
- so calling this method would close the page.

2023-05-24 23:10 UTC, skumar09 commented on tests/uar/quiz.analytics.test.js
> +        console.log(networklogs);
- this would a lot of logging to the terminal, I would suggest commenting or removing this statement if there is no validation of logs done at the moment

2023-05-24 23:49 UTC, JackySun9 commented on libs/webutil.js
> +    await this.page.close();
yes, I removed the close() method

2023-05-24 23:49 UTC, JackySun9 commented on tests/uar/quiz.analytics.test.js
> +        console.log(networklogs);
ok

2023-05-25 01:13 UTC, skumar09 approved these changes

2023-05-26 19:49 UTC, amauch-adobe approved these changes
Approved.

2023-05-26 20:38 UTC, merged