config, env, folder structure setup for CC
adobecom/nala pull request #126
Opened 2023-06-01 09:55 UTC by sigadamvenkata

config, env, folder structure setup for CC onboarding

2023-06-01 22:18 UTC, skumar09 approved these changes

2023-06-01 22:18 UTC, skumar09 commented on tests/cc/febpub.test.js
> +test('ulr has html ext' , async({page}) =>
please pass `browser` object also to `test` method

Approving the PR, [ It's a initial PR to to onboard cc to Nala]

2023-06-01 22:24 UTC, JackySun9 requested changes

2023-06-01 22:24 UTC, JackySun9 commented on selectors/cc/febpub.selectors.js
> +module.exports = {
We are using Page Objects now, please check other code for sample

2023-06-01 22:25 UTC, JackySun9 requested changes

2023-06-01 22:25 UTC, JackySun9 commented on envs/envs.js
> +  '@cc_live' : 'https://main--cc--adobecom.hlx.live',
you don't have cc_prod here

2023-06-03 20:27 UTC, chadsunvice requested changes

2023-06-03 20:27 UTC, chadsunvice commented on selectors/cc/febpub.selectors.js
> +
For consistency all files end in newline, here there are trailing whitespaces.

2023-06-03 20:27 UTC, chadsunvice commented on features/cc/febpub.sanity.js
> +    name: 'fedpub Component',
Keep uppercase for component name to keep consistency with others (eg: `FedPub Component`, or `Fedpub Component`), look cleaner in reports.

2023-06-03 20:27 UTC, chadsunvice commented on features/cc/febpub.sanity.js
> +
For consistency all files end in newline, here there are trailing whitespaces.

2023-06-03 20:27 UTC, chadsunvice commented on tests/cc/febpub.test.js
> +{await page.goto('https://www.stage.adobe.com/creativecloud/photography/hub/guides/camera-settings-for-rain-photography')} );
We should avoid hardcoding URLs. Also format the code better. 

```
test('URL has html extension' , async({page}) => {
  await page.goto('https://www.stage.adobe.com/creativecloud/photography/hub/guides/camera-settings-for-rain-photography')};
  await expert(page).toHaveURL('html');
});
```

2023-06-03 20:27 UTC, chadsunvice commented on tests/cc/febpub.test.js
> +await expert(page).toHaveURL('html');
For consistency all files end in newline, here there are trailing whitespaces.

2023-06-09 10:56 UTC, sigadamvenkata commented on selectors/cc/febpub.selectors.js
> +
removed the newline spaces

2023-06-09 10:57 UTC, sigadamvenkata commented on features/cc/febpub.sanity.js
> +
removed

2023-06-09 10:57 UTC, sigadamvenkata commented on tests/cc/febpub.test.js
> +{await page.goto('https://www.stage.adobe.com/creativecloud/photography/hub/guides/camera-settings-for-rain-photography')} );
removed

2023-06-12 09:46 UTC, chadsunvice approved these changes
Looks good!

2023-06-12 17:49 UTC, JackySun9 approved these changes

2023-06-13 05:16 UTC, merged