[MWPW-131179] Added Jarvis supporting logic, desktop/mobile checks
adobecom/nala pull request #132
Opened 2023-06-14 16:57 UTC by chadsunvice

PR relates to story [MWPW-131179](https://jira.corp.adobe.com/browse/MWPW-131179): Develop FEDS Jarvis checks on NALA.

2023-06-15 17:25 UTC, JackySun9 approved these changes

2023-06-16 10:47 UTC, chadsunvice commented on features/feds/jarvis.spec.js
> +      envs: '@milo_live',
I don't agree with this change. We were asked to migrate towards running our checks on `@milo_live`. All the paths are available on the Milo ecosystem.

You can check the following:
1. Milo Prod: https://milo.adobe.com/libs/feds/drafts/qa/jarvis/feds-jarvis-mobile
2. Milo Live: https://main--milo--adobecom.hlx.live/libs/feds/drafts/qa/jarvis/feds-jarvis-mobile
3. Milo Page: https://main--milo--adobecom.hlx.page/libs/feds/drafts/qa/jarvis/feds-jarvis-mobile

All the above pages work just fine. What is the concerne here @skumar09 ? Also, please provide alternatives when suggesting a change. This way we can avoid ping-pong of review comments and have speedier merges.

2023-06-16 10:49 UTC, chadsunvice commented on selectors/feds/feds.footer.page.js
>      this.DownloadAdobeExpress = page.locator('footer a[daa-ll="Adobe_Express"]');
I might do this in the future, we like the upper-case first variant for the page-object selectors. This should be done in a separate PR, for consistency purposes. If I change it here, these are still multiple cases where the others are in the same format. Ignoring this time.

2023-06-16 15:42 UTC, skumar09 commented on selectors/feds/feds.footer.page.js
>      this.DownloadAdobeExpress = page.locator('footer a[daa-ll="Adobe_Express"]');
- sure..

2023-06-16 15:44 UTC, skumar09 approved these changes

2023-06-22 19:47 UTC, amauch-adobe requested changes
Looks great, made some comments that may/may not need changing but I figured you might want to be consistent with your imports from your PR that came after this one.

2023-06-22 19:47 UTC, amauch-adobe commented on tests/feds/jarvis.desktop.test.js
> +const JarvisSpec = require('../../features/feds/jarvis.spec.js');
Did you want this to be similar to your other ESLint changes and make this an "import *" statement over "const/require"?

2023-06-22 19:47 UTC, amauch-adobe commented on tests/feds/jarvis.mobile.test.js
> +
Same comment as the desktop test, would you prefer to change the const/require statement to an import/* statement like you have done in another PR with Lint changes?

2023-06-22 19:47 UTC, amauch-adobe commented on tests/feds/jarvis.mobile.test.js
> +
Just an FYI in the future as we get more mobile tests it will be best for us to move this viewport logic to the respective team config or even create a separate mobile config for the team.  I think this is fine where it is just one test, but certainly for maintainability in the future where we might have more, it would be best to have it in the config file under a separate project config name.  I think Playwright even provides some configs for Android, iPhone, and iPad as well.

2023-06-22 22:47 UTC, skumar09 commented on tests/feds/jarvis.mobile.test.js
> +
yeah, i agree with @amauch-adobe  on this

2023-06-23 01:55 UTC, chadsunvice commented on tests/feds/jarvis.desktop.test.js
> +const JarvisSpec = require('../../features/feds/jarvis.spec.js');
Agree! Wanted consistent importing across files so we don't have a soup of import/require. Nice spot!

2023-06-23 01:57 UTC, chadsunvice commented on tests/feds/jarvis.mobile.test.js
> +
I totally agree. We should have Android/iPhone configs and run the checks as mobile. I will update these tomorrow. I knew about them, but it was a quick way to test if Jarvis is rendering on mobile-viewport.

2023-06-23 01:58 UTC, chadsunvice commented on tests/feds/jarvis.mobile.test.js
> +
Agree! Wanted consistent importing across files so we don't have a soup of import/require. Nice spot!

2023-07-10 20:09 UTC, chadsunvice commented
@amauch-adobe, @skumar09, please re-review.

- I removed ` › ` with `, ` as mentioned in the previous reviews (PR from @iamdanchiv account)
- talked with Narcis and as Milo is using ES6, we want to pursue using only `imports`, also file foot-print is smaller (1 import, vs. 1 require + 1 constant variable assignment)
- now only importing `{ features }`, which uses the exact information required
- ran checks locally and on remote and nothing was failing, if any concerns, please reply with failing run to re-assess
- rest of the issues we can tackle in a future PR if required, for now let's merge these as is

2023-07-10 21:43 UTC, amauch-adobe approved these changes
Approved. Looks good to me.

2023-07-10 21:43 UTC, amauch-adobe commented on tests/feds/jarvis.desktop.test.js
> +import { features } from '../../features/feds/jarvis.spec.js';
Thanks for sticking to ES6 and making the change to this format of import.

2023-07-10 21:44 UTC, amauch-adobe commented
@chadsunvice make sure to make the camelCase adjustments that @skumar09 mentioned.

2023-07-11 09:23 UTC, merged