[MWPW-131179] Added Jarvis NALA checks & supporting logic
adobecom/nala pull request #137
Opened 2023-06-26 08:25 UTC by iamdanchiv

PR relates to story [MWPW-131179](https://jira.corp.adobe.com/browse/MWPW-131179): Develop FEDS Jarvis checks on NALA.

2023-06-27 13:43 UTC, iamdanchiv commented
Closing to activate Adobe Signed CLA. Re-opening after.

2023-06-27 19:03 UTC, JackySun9 requested changes

2023-06-27 19:03 UTC, JackySun9 commented on tests/feds/jarvis.desktop.test.js
> +import * as JarvisSpec from '../../features/feds/jarvis.spec.js';
We don't want star here

2023-06-27 19:16 UTC, amauch-adobe requested changes
Everything looks great, just that one concern of using "import *" with our spec.js files since it fails runtime execution as mentioned in PR #138

2023-06-27 19:16 UTC, amauch-adobe commented on tests/feds/jarvis.desktop.test.js
> +import * as JarvisSpec from '../../features/feds/jarvis.spec.js';
Same concern mentioned in my comments on your PR #138.  Sorry again for not checking that out before.

2023-06-27 19:16 UTC, amauch-adobe commented on tests/feds/jarvis.mobile.test.js
> +import * as JarvisSpec from '../../features/feds/jarvis.spec.js';
The same here on the need to use require() instead of "import *" where we are using CommonJS modules.export structure for spec files.  I think it would be provincial for us to look into seeing if updating spec files as separate export declarations would be a viable option so we could be more ES6 compliant, though.

2023-07-04 12:20 UTC, iamdanchiv commented on tests/feds/jarvis.desktop.test.js
> +import * as JarvisSpec from '../../features/feds/jarvis.spec.js';
I've read your concerns @amauch-adobe from [PR #138](https://github.com/adobecom/nala/pull/138#pullrequestreview-1501665646), and I don't fully agree. I think we should start the migration to ES6 right away.

I updated the scripts to import `{ features }` instead of `*`, and I hope this is an agreeable middle ground. I've also ran the checks multiple times in several envs and they never fail. Can you provide runs where this approach fails? I was unable to reproduce a scenario where these fail, especially since we use imports already.

Please give palpable examples as to why we shouldn't use `imports` everywhere and still use CommonJS logic. Also the fact that this is 100% asynchronous should support the ethos of a PlayWright framework even more.

Cc: @narcis-radu, @skumar09, @JackySun9

2023-07-04 12:20 UTC, iamdanchiv commented on tests/feds/jarvis.mobile.test.js
> +import * as JarvisSpec from '../../features/feds/jarvis.spec.js';
I've read your concerns @amauch-adobe from [PR #138](https://github.com/adobecom/nala/pull/138#pullrequestreview-1501665646), and I don't fully agree. I think we should start the migration to ES6 right away.

I updated the scripts to import `{ features }` instead of `*`, and I hope this is an agreeable middle ground. I've also ran the checks multiple times in several envs and they never fail. Can you provide runs where this approach fails? I was unable to reproduce a scenario where these fail, especially since we use imports already.

Please give palpable examples as to why we shouldn't use `imports` everywhere and still use CommonJS logic. Also the fact that this is 100% asynchronous should support the ethos of a PlayWright framework even more.

Cc: @narcis-radu, @skumar09, @JackySun9

2023-07-04 12:21 UTC, iamdanchiv commented
I've read your concerns @amauch-adobe from [PR #138](https://github.com/adobecom/nala/pull/138#pullrequestreview-1501665646), and I don't fully agree. I think we should start the migration to ES6 right away.

I updated the scripts to import `{ features }` instead of `*`, and I hope this is an agreeable middle ground. I've also ran the checks multiple times in several envs and they never fail. Can you provide runs where this approach fails? I was unable to reproduce a scenario where these fail, especially since we use imports already.

Please give palpable examples as to why we shouldn't use `imports` everywhere and still use CommonJS logic. Also the fact that this is 100% asynchronous should support the ethos of a PlayWright framework even more.

Cc: @narcis-radu, @skumar09, @JackySun9

2023-07-06 11:54 UTC, narcis-radu commented on selectors/feds/feds.jarvis.page.js
> +exports.FedsJarvis = class FedsJarvis {
should use `module.exports`

2023-07-06 14:28 UTC, narcis-radu approved these changes

2023-07-10 15:45 UTC, closed without merging