MWPW-133388 : Georouting feature test scripts
adobecom/nala pull request #140
Opened 2023-06-30 09:01 UTC by skumar09

[MWPW-133388 ](https://jira.corp.adobe.com/browse/MWPW-133388): Georouting feature test scripts
PR includes
- Georouting modal ( i.e. user accessing "de" page from "us" locale )
- Georouting modal with query param (ex: akamaiLocale=DE)
- Georouting through the 'Change region' modal
- Georouting modal with multi-tabs
- Georouting-Off
- Georouting modal close

Info:
- Georouting fallback options related test cases are pending for clarification

2023-06-30 11:54 UTC, iamdanchiv commented on selectors/milo/georouting.feature.page.js
> +}
Missing trailing newline in file.

2023-06-30 11:54 UTC, iamdanchiv commented on selectors/milo/georouting.feature.page.js
> +        try{
try { (missing space)

2023-06-30 11:54 UTC, iamdanchiv commented on features/milo/georouting.spec.js
> +      tcid: '0',
These `tcid`'s have no use in our checks and I don't see why we would continue using them. They are confusing and also strings instead of numbers. I propose we stop adding `tcid`'s and slowly remove them from the files. We should have Jira ticket as a way to identify the checks.

2023-06-30 11:54 UTC, iamdanchiv commented on tests/milo/georouting.feature.test.js
> +    // Test - 0
These comments `// Test - 0` should also be removed and have some short comprehensive descriptions. Imagine in the future when other clients will add their tests in these files (eg: new Marquee variant, new Text variant), we will maybe have a different order, or EVEN WORSE, we find out one check si DEPRECATED, then when we remove it, all the indexes in `tcid`'s and the `// Test - 0` comments, will have to shift.

2023-06-30 11:54 UTC, iamdanchiv commented on tests/milo/georouting.feature.test.js
> +
Extra empty line here.

2023-06-30 11:54 UTC, iamdanchiv commented on tests/milo/georouting.feature.test.js
> +    });
Could we please change `obj` to something more descriptive like `geoObject`?

2023-06-30 11:54 UTC, iamdanchiv commented on selectors/milo/georouting.feature.page.js
> +    }
There is an extra 2-space indentation for the methods blocks. Please align with the constructor level of indentation.

2023-06-30 17:41 UTC, skumar09 commented on features/milo/georouting.spec.js
> +      tcid: '0',
- tcid is  `test case id` and currently it is a placeholder for Jira id / Test rail id, It will be updated later

2023-06-30 17:43 UTC, JackySun9 requested changes

2023-06-30 17:43 UTC, JackySun9 commented on selectors/milo/georouting.feature.page.js
> +export default class Georouting {
should we use this: exports.GeoRouting = class GeoRouting like we did for others

2023-06-30 17:43 UTC, JackySun9 commented on features/milo/georouting.spec.js
> +      tcid: '0',
We can have this now and update it as JIRA id later

2023-06-30 17:49 UTC, skumar09 commented on tests/milo/georouting.feature.test.js
> +    // Test - 0
- I think, we can remove these comments, they are just for readability purposes
- On the order of test cases, i think In Milo, each test cases are standalone, and are in sync with the spec order, ( as such there is no order or sequence required.)

2023-06-30 18:14 UTC, skumar09 commented on tests/milo/georouting.feature.test.js
> +    });
- I had thought about this, but then settled on `obj` as it is a bit short and generic, even though I am not fully fine with it
- what I was not liking was something below one when using a bit more lengthy/descriptive naming 
      - ex: `geoObject.geoModal` , or `geoObject.geoModalClose` or `geoObject.changeRegionModal etc..
- I also think, we need some more brainstorming or discussion around this, we can discuss this in our calls
- for the time being, I will keep `obj,`

2023-06-30 18:32 UTC, skumar09 commented on selectors/milo/georouting.feature.page.js
> +export default class Georouting {
- @JackySun9: This is a good point, I have an upcoming pr lined up for this, to update to `ES6 `module system for poms.

2023-06-30 19:23 UTC, JackySun9 approved these changes

2023-06-30 20:23 UTC, amauch-adobe requested changes
Looks Awesome! Just had some ideas for potential changes, but not critical for functioning.

As way of information for Fallback testing this is something I asked Victor while first creating the original test:

Aaron - "If fallback routing is turned off for a page, but georouting is turned on, shouldn't you still see a modal popup?  Or am I thinking incorrectly?"

Victor - "Yes, but only if there is a valid locale sibling for the page you're trying to visit. In your case if the page
https://main--milo--adobecom.hlx.live/de/test/features/blocks/georouting-fallback-off?akamaiLocale=DE
existed, then the modal would appear."

2023-06-30 20:23 UTC, amauch-adobe commented on selectors/milo/georouting.feature.page.js
> +            await expect(this.geoModal.locator(`//a[text()="${data.button}"]`)).toBeVisible({ timeout: 1000 });
Is there a need for timeouts for these specific elements?

2023-06-30 20:23 UTC, amauch-adobe commented on tests/milo/georouting.feature.test.js
> +    });
I agree that it would be good to find a name that would work over obj, but I do understand the desire to not have something so long too.  Maybe geoModal, popup, or just modal?

2023-06-30 20:23 UTC, amauch-adobe commented on tests/milo/georouting.feature.test.js
> +        await test.step('step-1: Clear cookies and access "us" page with query param (akamailLocale=DE)', async () => {
might be best to capitalize "US" since it is a region.

2023-06-30 20:23 UTC, amauch-adobe commented on tests/milo/georouting.feature.test.js
> +        await test.step('step-1: Clear cookies and access "us" page', async () => {
same case here, capitalize "US"

2023-06-30 20:23 UTC, amauch-adobe commented on tests/milo/georouting.feature.test.js
> +        await test.step('step-3: Click "de" button and then verify international cookie value', async () => {
Maybe change "de" button to what is the actual text of the button for clarity.

2023-06-30 20:23 UTC, amauch-adobe commented on tests/milo/georouting.feature.test.js
> +        await test.step('step-1: Clear cookies and access "us" page', async () => {
same here "US" capitalizing.

2023-06-30 20:30 UTC, skumar09 commented on selectors/milo/georouting.feature.page.js
> +            await expect(this.geoModal.locator(`//a[text()="${data.button}"]`)).toBeVisible({ timeout: 1000 });
yeah, the timeouts were required here, during debugging I have observed some slowness, and it's the maximum timeout

2023-06-30 21:33 UTC, amauch-adobe approved these changes

2023-06-30 23:15 UTC, Dli3 approved these changes

2023-07-01 04:00 UTC, Ruchika4 approved these changes

2023-07-02 13:18 UTC, iamdanchiv approved these changes
LGTM!

2023-07-03 18:49 UTC, merged