[MWPW-133840] FEDS check improvements & ES6 support
adobecom/nala pull request #143
Opened 2023-07-17 19:12 UTC by chadsunvice

PR relates to ticket [[NALA-Automation] Update FEDS checks (test improvements & ES6 support)](https://jira.corp.adobe.com/browse/MWPW-133840).

Added:
- support for non-US runs to not display the GeoRouting modal (impairing other page actions)
- transitioned to ES6 way of declaring classes/instantiating class objects to match Milo logic
- improved Jarvis checks (extra checks and assertions)

2023-07-17 19:49 UTC, skumar09 requested changes

2023-07-17 19:49 UTC, skumar09 commented on tests/feds/consent.test.js
> +      await page.goto(`${baseURL}${features[0].path}?customPrivacyLocation=de&hideGeorouting=on`);
I think we can define it as a global scoped variable or constant and then use it, instead of changing 
it in every first `test.step()`, of a `test()` 
something like below
`const hideGeoroutingQueryParam = '?hideGeorouting=on'`;
`await page.goto(${baseURL}${features[0].path}${hideGeoroutingQueryParam});`

Also, we can think of defining a property in `.spec.js `and use it in the test.step()
`hideGeo : 'hideGeorouting=on',`
`await page.goto(${baseURL}${features[0].path}${features[0].hideGeo});`

2023-07-17 23:03 UTC, amauch-adobe requested changes
Looks really good, just some nitpicks I found, also I agree with @skumar09 that it would be best to use a global/spec/page variable for the URL parameter to hide georouting modal since it is used across many test files.

2023-07-17 23:03 UTC, amauch-adobe commented on tests/feds/jarvis.desktop.test.js
> +      // Open Jarvis chat assistent (via header button):
Should this say "Close" in the comments instead of "Open" since the check is verifying it isn't visible?

2023-07-18 13:27 UTC, chadsunvice commented on tests/feds/jarvis.desktop.test.js
> +      // Open Jarvis chat assistent (via Jarvis button):
Haha, yes, I agree @amauch-adobe! The Romanian in me doubled the s but wrote it as in my native language. Old-habits and no spell check in VSCode will do this. 😄

2023-07-18 13:33 UTC, chadsunvice commented on tests/feds/jarvis.desktop.test.js
> +      // Open Jarvis chat assistent (via Jarvis button):
Fixed! 👍

2023-07-18 13:33 UTC, chadsunvice commented on tests/feds/jarvis.desktop.test.js
> +      // Open Jarvis chat assistent (via header button):
Fixed! 👍

2023-07-18 13:33 UTC, chadsunvice commented on tests/feds/jarvis.desktop.test.js
> +      // Open Jarvis chat assistent (via Jarvis button):
Fixed! 👍

2023-07-18 15:51 UTC, chadsunvice commented on tests/feds/consent.test.js
> +      await page.goto(`${baseURL}${features[0].path}?customPrivacyLocation=de&hideGeorouting=on`);
Fixed! Added per-spec file approach since we will have different mixes of browser params which will switch per test type. We already have the consent checks which are a corner-case, so sticking to the second approach. Considered the `feds.config.js` approach, but it was more custom-coding in order to make it work.

2023-07-18 19:24 UTC, skumar09 approved these changes
- Minor review comments, approving the PR, 
- I have added a single review comment that applies to all files. Please review and update accordingly

2023-07-18 19:24 UTC, skumar09 commented on features/feds/breadcrumbs.spec.js
> +      browserParams: '?hideGeorouting=on',
It is just a perspective, you can take the call 
- from a terminology standpoint, it is referred to as a `query parameter`, you may want to consider using something like `queryParam`, 
- If it is commonly called a `browser parameter` in the applications, then `browserParams` would be easily understood by all

2023-07-18 19:24 UTC, skumar09 commented on tests/feds/header.test.js
>  /* eslint-disable import/extensions */
i think` /* eslint-disable import/extensions */` is not required

2023-07-18 19:32 UTC, amauch-adobe approved these changes
Approved!

2023-07-19 09:37 UTC, chadsunvice commented on features/feds/breadcrumbs.spec.js
> +      browserParams: '?hideGeorouting=on',
We usually call them browser params since it happens in the scope of the browser, the full naming being `URL query params`, so we default to `browser params` as a way to shorten it. The naming isn't critical as long as we know that they now reside in the `spec` files.

2023-07-19 09:37 UTC, merged