MWPW-133863 : Icon block tests scripts
adobecom/nala pull request #144
Opened 2023-07-17 23:43 UTC by skumar09

[MWPW-133863 ](https://jira.corp.adobe.com/browse/MWPW-133863 ): Icon block tests scripts

PR includes 
- Automation test scripts for the following features of the Icon block

   - Icon block (fullwidth, medium) 
   - Icon block (fullwidth, medium, intro)
   - Icon block (fullwidth,large)

2023-07-18 04:06 UTC, JackySun9 approved these changes

2023-07-18 13:56 UTC, chadsunvice requested changes

2023-07-18 13:56 UTC, chadsunvice commented on selectors/milo/icon.block.page.js
> +export class Icon {
We should use `export default class` and import with `import ClassName from <path>` since there is only one class being exported/imported from these specific files, as per [PR#143](https://github.com/adobecom/nala/pull/143) to match Milo style.

2023-07-18 13:56 UTC, chadsunvice commented on selectors/milo/icon.block.page.js
> +      'icon-fullwidth-medium': {class: 'icon-block fullwidth medium con-block',},
Extra `,` & spacing inconsistency: `'icon-fullwidth-medium': { class: 'icon-block fullwidth medium con-block' },`

2023-07-18 17:54 UTC, amauch-adobe requested changes
Everything looked good to me, just the small nitpick.  Also, it would be good to look into the requested changes Daniel shared too.

2023-07-18 17:54 UTC, amauch-adobe commented on features/milo/icon.block.spec.js
small nit pick, there is an extra comma at the end of each of the "tags" variables that should be removed.

2023-07-18 19:30 UTC, amauch-adobe approved these changes
Approved, but just want to know about the comma in the tags on the spec.js file.

2023-07-18 19:30 UTC, amauch-adobe commented on features/milo/icon.block.spec.js
> +        tags: '@icon @icon-fullwidth-medium @smoke @regression @milo,',
should there be a comma at the end of the last tag?

2023-07-18 19:30 UTC, amauch-adobe commented on features/milo/icon.block.spec.js
> +        tags: '@icon @icon-fullwidth-medium-intro @smoke @regression @milo,',
should there be a comma at the end of the last tag?

2023-07-18 19:30 UTC, amauch-adobe commented on features/milo/icon.block.spec.js
> +        tags: '@icon @icon-fullwidth-large, @smoke @regression @milo,',
should there be a comma at the end of the last tag?

2023-07-18 19:53 UTC, skumar09 commented on features/milo/icon.block.spec.js
@amauch-adobe : this one is across .`spec.js`, I am raising another pr with some failure fixes, and will take care of this one in it.

2023-07-18 21:19 UTC, amauch-adobe commented on features/milo/icon.block.spec.js
@skumar09 sounds good.

2023-07-19 08:39 UTC, narcis-radu commented on selectors/milo/icon.block.page.js
> +export class Icon {
Hi @skumar09 - why are named exports preferred over default exports? I think we should have consistency with milo, but maybe there's something that I'm missing. cc @amauch-adobe , @auniverseaway.
Let me know if this requires a community discussion, I'm happy to start one.

2023-07-19 09:54 UTC, chadsunvice requested changes

2023-07-19 09:54 UTC, chadsunvice commented on selectors/milo/icon.block.page.js
> +      'icon-fullwidth-large' : { class: 'icon-block fullwidth large con-block'},
Maintain spacing consistency: 

```
      'icon-fullwidth-medium': {class: 'icon-block fullwidth medium con-block'},
      'icon-fullwidth-medium-intro': {
        class:
          'icon-block fullwidth medium intro con-block xxxl-spacing-top xl-spacing-static-bottom'
      },
      'icon-fullwidth-large' : { class: 'icon-block fullwidth large con-block'},
```
     vs. 
     
```
      'icon-fullwidth-medium': { class: 'icon-block fullwidth medium con-block' },
      'icon-fullwidth-medium-intro': {
        class:
          'icon-block fullwidth medium intro con-block xxxl-spacing-top xl-spacing-static-bottom'
      },
      'icon-fullwidth-large' : { class: 'icon-block fullwidth large con-block' },

2023-07-19 19:55 UTC, amauch-adobe commented on selectors/milo/icon.block.page.js
> +export class Icon {
@narcis-radu we are going to discuss this in Nala with everyone.  I was also going to do some research myself, the biggest thing we have found which is a rare case, and is more of an exception than anything, is default exports don't allow you to have multiple exports in POM file, at least I think that is the case.  As I mentioned it is a small use case and a very rare one. Other than that it allows us to avoid having to disable ESLint warnings, although this could be handled by adding to the ESLint configuration to ignore such things too.

2023-07-19 21:27 UTC, skumar09 commented on selectors/milo/icon.block.page.js
> +export class Icon {
> Hi @skumar09 - why are named exports preferred over default exports? I think we should have consistency with [milo](https://github.com/adobecom/milo/blob/main/libs/features/georoutingv2/georoutingv2.js#L262), but maybe there's something that I'm missing, I thought both projects would follow the same directions.. cc @amauch-adobe , @auniverseaway. Let me know if this requires a community discussion, I'm happy to start one. @chadsunvice


Hi @narcis-radu :

* I think, In the Milo project, we have a few `named exports`, with the `default export` being the main one.
* The main reason for using `named exports` is to **restrict importing with any arbitrary name** and to **avoid ESLint warnings.**
* I had a brief discussion with @chrischrischris  and what understand is it doesn't significantly impact the outcome. However, the widely accepted standard is that if you are exporting a single module, having a default export is considered the norm.
* I also think that, need to do a bit more analysis on this with respect to other requirements/features and discuss in the Nala group and take it forward.
@amauch-adobe  @auniverseaway  @chrischrischris @JackySun9 @chadsunvice

2023-07-20 08:29 UTC, narcis-radu commented on selectors/milo/icon.block.page.js
> +export class Icon {
Thanks for the explanation @skumar09. I haven't seen any ESLint warning in Milo regarding using arbitrary names for imported modules, maybe we can get the same set of rules in Nala and allow engineers to contribute to both projects without the need to switch context and directives.
I'm happy this topic is being actively discussed and I hope to get more feedback from the Nala / Milo community once a thread will be created. Thank you for handling all aspects.

2023-07-20 21:43 UTC, skumar09 commented on selectors/milo/icon.block.page.js
> +export class Icon {
> Thanks for the explanation @skumar09. I haven't seen any ESLint warning in Milo regarding using arbitrary names for imported modules, maybe we can get the same set of rules in Nala and allow engineers to contribute to both projects without the need to switch context and directives. I'm happy this topic is being actively discussed and I hope to get more feedback from the Nala / Milo community once a thread will be created. Thank you for handling all aspects @amauch-adobe and @skumar09!

Hi @narcis-radu 
Thank you for the review and inputs, I will keep you updated on this topic.

2023-07-20 21:46 UTC, skumar09 commented on selectors/milo/icon.block.page.js
> +export class Icon {
Note: will be merging this pr, ( for the `module export` topic, will update as per the discussion)

2023-07-21 11:11 UTC, chadsunvice approved these changes

2023-07-21 18:02 UTC, merged