Text block legal, link-farm variations automation
adobecom/nala pull request #146
Opened 2023-07-21 16:52 UTC by sigadamvenkata

Text block legal, link-farm variations automation
Ran all text block suite (total 8) cases are passing

2023-07-21 18:15 UTC, skumar09 requested changes

2023-07-21 18:15 UTC, skumar09 commented on features/milo/text.block.spec.js
> +      tags: '@text @smoke @regression @milo,',
please remove the `','` after `@milo` tag

2023-07-21 18:15 UTC, skumar09 commented on selectors/milo/text.block.page.js
> + * text (full-width, large), text (long form, large), and text (inset, large, m spacing), text (legal), text (link-farm)
very minor comment: please add to new line, ( `max allowed line length is 100 char` )

2023-07-21 18:15 UTC, skumar09 commented on selectors/milo/text.block.page.js
> + * text (full-width, large), text (long form, large), and text (inset, large, m spacing), text (legal), text (link-farm)
@sigadamvenkata : PR looks good, just few mionr review comments

2023-07-21 20:20 UTC, chadsunvice approved these changes

2023-07-24 06:04 UTC, sigadamvenkata commented on features/milo/text.block.spec.js
> +      tags: '@text @smoke @regression @milo,',
Done santosh. thanks
https://github.com/adobecom/nala/pull/146/commits/4170bc33f6092d0e4249924df168a5c0333e3670

2023-07-24 06:05 UTC, sigadamvenkata commented on selectors/milo/text.block.page.js
> + * text (full-width, large), text (long form, large), and text (inset, large, m spacing), text (legal), text (link-farm)
done, please check
https://github.com/adobecom/nala/pull/146/commits/5a31d887a733d3ed4bddb41c3579fbe534d87f7d

2023-07-24 19:40 UTC, skumar09 approved these changes

2023-07-24 19:41 UTC, merged