[MWPW-133606] Aside block automated scripts
adobecom/nala pull request #151
Opened 2023-08-14 14:02 UTC by chadsunvice

PR raised in scope of ticket **[[MWPW-133606](https://jira.corp.adobe.com/browse/MWPW-133606)]: Aside Block: Create Nala Automation Test script** .

2023-08-14 22:05 UTC, amauch-adobe requested changes
see my comments above.

2023-08-15 15:13 UTC, chadsunvice commented on features/milo/aside.block.spec.js
> +      tags: '@aside, @aside-small, @smoke, @regression @milo',
Goot catch @amauch-adobe, updated!

2023-08-15 15:13 UTC, chadsunvice commented on features/milo/aside.block.spec.js
> +      tags: '@aside, @aside-split-medium, @smoke, @regression @milo',
Updated!

2023-08-15 16:56 UTC, JackySun9 requested changes

2023-08-15 16:56 UTC, JackySun9 commented on features/milo/aside.block.spec.js
> +      browserParams: '?hideGeorouting=on',
if browserParams are all the same, why do you put it here?

2023-08-15 16:56 UTC, JackySun9 commented on tests/milo/aside.block.test.js
> +      await expect(Aside.asideSmall).toBeVisible();
Because almost all steps are the same, could you have them in a internal function?

2023-08-15 20:29 UTC, chadsunvice commented on tests/milo/aside.block.test.js
> +      await expect(Aside.asideSmall).toBeVisible();
The steps are actually not the same. Each Aside block has specific particularities. Maybe some tests have overlapping logic, but the checks are not all the same. Most of them use check different configs of classes and selectors change based on that. 

eg: One Aside block has smallText, others have mediumText. One Aside block has picture, another doesn't. These are particular to every Aside type of block.

2023-08-16 01:16 UTC, JackySun9 approved these changes

2023-08-17 20:28 UTC, chadsunvice commented
> see my comments above.

Updated!

2023-08-21 16:55 UTC, skumar09 reviewed
@chadsunvice: PR looks good; just following a few points
- do we want to add CSS / attributes validations, Or do you want to take care later?

2023-08-21 16:55 UTC, skumar09 commented on tests/milo/aside.block.test.js
> +    console.info(`[MiloInfo] Checking page: ${baseURL}${features[9].path}`);
please change the console.info to format : `console.info(`[Test Page]: ${baseURL}${features[0].path}`);`

2023-08-21 16:58 UTC, skumar09 commented on tests/milo/aside.block.test.js
> +      expect(await Aside.actionButtons.count()).toEqual(2);
- for the Aside block,  actionButtons count will always be 2 or is it configurable? if configuration about adding counts to `.spec.js` or `global`

2023-08-21 17:31 UTC, chadsunvice commented on tests/milo/aside.block.test.js
> +      expect(await Aside.actionButtons.count()).toEqual(2);
If you look at the entire test-suite, you'll notice there is not real rule enforced throughout the feature. Some Aside blocks have 1 button, some have both, some have only one CTA link. There's really no clear rule here.

2023-08-21 17:31 UTC, chadsunvice commented on tests/milo/aside.block.test.js
> +    console.info(`[MiloInfo] Checking page: ${baseURL}${features[9].path}`);
Updated!

2023-08-21 17:33 UTC, chadsunvice commented
> @chadsunvice: PR looks good; just following a few points
> 
> * do we want to add CSS / attributes validations, Or do you want to take care later?

I talked to Narcis and also got some feedback from our Devs that there are still Aside changes happening so this will mean most of the checks will become brittle. I would wait for development to stabilise and then take some conclusions on this. 

Also we feel CSS validation isn't something that will change, and attributes are already tested via the selectors that have them in their composition. So I would say wait on this.

2023-08-21 19:04 UTC, skumar09 approved these changes

2023-08-22 01:34 UTC, amauch-adobe approved these changes
Approved.

2023-08-22 05:18 UTC, merged