 MWPW-135564 : Upgrade Playwright to the latest version (1.37)
adobecom/nala pull request #155
Opened 2023-08-24 20:01 UTC by skumar09

2023-08-24 20:20 UTC, amauch-adobe requested changes
I wasn't at Nala Refinement, so there may have been a discussion for not going any higher than version 1.37, but looking at the github site for playwright version 1.37.1 is the latest.  Should we upgrade to that version to get the patch update?

![Screenshot 2023-08-24 at 2 19 25 PM](https://github.com/adobecom/nala/assets/56042473/23cbadbb-0cec-48c6-b8b7-e2c56f39f2da)

2023-08-24 20:26 UTC, skumar09 commented
> I wasn't at Nala Refinement, so there may have been a discussion for not going any higher than version 1.37, but looking at the github site for playwright version 1.37.1 is the latest. Should we upgrade to that version to get the patch update?
> 
> ![Screenshot 2023-08-24 at 2 19 25 PM](https://user-images.githubusercontent.com/56042473/263097185-23cbadbb-0cec-48c6-b8b7-e2c56f39f2da.png)

@amauch-adobe From playwright release notes I see the latest approved `version as 1.37.` , 
https://playwright.dev/docs/release-notes

2023-08-24 20:34 UTC, Dli3 approved these changes

2023-08-24 20:35 UTC, amauch-adobe approved these changes
@skumar09 and @Dli3 all discussed with me about sticking with v1.37 for now and if needed moving to 1.37.1.

2023-08-24 21:33 UTC, JackySun9 approved these changes

2023-08-25 06:09 UTC, chadsunvice approved these changes

2023-08-25 06:52 UTC, merged