Create dynamic test cases for UAR
adobecom/nala pull request #156
Opened 2023-08-24 22:32 UTC by JackySun9

https://jira.corp.adobe.com/browse/MWPW-134029
https://jira.corp.adobe.com/browse/MWPW-124778

1. build test data for manual and automation
2. build test cases according to source json files
3. build automation based on dynamic test data
4. run automation side by side on prod and uar-integration

2023-08-25 04:30 UTC, amauch-adobe requested changes
See my comments throughout.

2023-08-25 17:06 UTC, JackySun9 commented on libs/webutil.js
> +const { request } = require('@playwright/test');
yes, we do, it is using to load json files

2023-08-28 18:48 UTC, JackySun9 commented on features/uar/quiz.dynamic.spec.js
data may be something else later

2023-08-28 18:50 UTC, JackySun9 commented on features/uar/quiz.dynamic.spec.js
will add @smoke and @regression later

2023-08-28 19:57 UTC, amauch-adobe requested changes
see my one question, but excellent job on the changes.

2023-08-28 19:57 UTC, amauch-adobe commented on package.json
> +    "test:uar": "npx playwright test --config=./configs/uar.config.js --project=uar-live-chrome --headed -g"
I want to be careful not to overload the package.json file in the main Nala repo.  Obviously when this project finally is made into a consumable project, then separate teams can choose to add whatever they would like in their package.json file going forward.  I remember Chris Millar wanting the package.json file to remain slim and not overloaded with different ways of executing the project (at least in this file) since it becomes difficult to read or find the execution you need.  That being said I was wondering if you couldn't use the current run.sh file to correctly send in your config and project (which I believe it is capable of doing), @skumar09 can correct me if I'm wrong.  I think the only thing that isn't currently available through the run.sh file is the '--headed' flag.  I think as a recommendation we should just add that ability to the type of flags available for executing run.sh so that we don't start having project-specific executions in the package.json file.  @skumar09, @JackySun9 , @chadsunvice , @Dli3 what do you think?

2023-08-28 20:35 UTC, JackySun9 commented on package.json
> +    "test:uar": "npx playwright test --config=./configs/uar.config.js --project=uar-live-chrome --headed -g"
let us wait for other comments on this

2023-08-28 23:04 UTC, skumar09 requested changes

2023-08-28 23:04 UTC, skumar09 commented on package.json
> +    "test:uar": "npx playwright test --config=./configs/uar.config.js --project=uar-live-chrome --headed -g"
@JackySun9 : 

- Let's not add any additional test run commands in `.package.json `for consuming projects 
- Ideally, when the Nala package is consumed (in the future), you can run both UI/non-ui modes for the corresponding project.

2023-08-29 01:18 UTC, JackySun9 commented on package.json
> +    "test:uar": "npx playwright test --config=./configs/uar.config.js --project=uar-live-chrome --headed -g"
ok, remove it

2023-08-30 19:12 UTC, chadsunvice approved these changes
Some small changes, but overall looks great @JackySun9!

2023-08-30 19:12 UTC, chadsunvice commented on selectors/uar/quiz.old.page.js
> +    console.log('==========old============');
I think we could remove this log.

2023-08-30 19:12 UTC, chadsunvice commented on selectors/uar/quiz.page.js
> +    console.log(newProduct.sort().join(''));
Same here, combine maybe?

2023-08-30 19:12 UTC, chadsunvice commented on selectors/uar/quiz.old.page.js
> +    if (text.includes('We think you\'ll love')) {
This value we check against should maybe be added in Quiz page props in case it changes in the future.

2023-08-30 20:01 UTC, skumar09 approved these changes

2023-08-30 22:35 UTC, JackySun9 commented on selectors/uar/quiz.old.page.js
> +    if (text.includes('We think you\'ll love')) {
let have this here, I can update it when we need

2023-08-30 22:44 UTC, JackySun9 commented on selectors/uar/quiz.page.js
> +    console.log(newProduct.sort().join(''));
merged

2023-08-30 22:44 UTC, JackySun9 commented on selectors/uar/quiz.old.page.js
> +    console.log('==========old============');
merged

2023-08-31 01:45 UTC, amauch-adobe approved these changes
Approved.

2023-08-31 01:46 UTC, merged