jarvis automation test cases
adobecom/nala pull request #158
Opened 2023-08-31 13:22 UTC by sigadamvenkata

jarvis automation test cases
Jira: MWPW-122175
test page: https://main--milo--adobecom.hlx.live/drafts/nala/features/jarvis/jarvis?georouting=off

2023-08-31 17:20 UTC, JackySun9 requested changes

2023-08-31 17:20 UTC, JackySun9 commented on tests/milo/javis.feature.test.js
> +      await page.waitForTimeout(6000);
better to use waitForSelector

2023-08-31 17:20 UTC, JackySun9 commented on tests/milo/javis.feature.test.js
> +    jarvischat = new Jarvis(page);
name convention, jarvisChat

2023-08-31 17:20 UTC, JackySun9 commented on selectors/milo/jarvis.feature.page.js
> +        this.jarvishelptext = page.locator('//*[contains(text(), "How can I help you")]');
This might need to change when move to non-English, do you have css or xpath

2023-08-31 21:21 UTC, amauch-adobe requested changes
see my small comments.  Great job by the way.

2023-08-31 21:21 UTC, amauch-adobe commented on tests/milo/javis.feature.test.js
> +     test(`${features[0].name}, ${features[0].tags}`, async ({ page, baseURL }) => {
this line is indented one too many.

2023-08-31 21:21 UTC, amauch-adobe commented on tests/milo/javis.feature.test.js
> +     console.info(`[Test Page]: ${baseURL}${features[0].path}`);
this line needs to be indented one more time.

2023-08-31 21:21 UTC, amauch-adobe commented on tests/milo/javis.feature.test.js
> +    await test.step('Validate the jarvis button launch the chat window', async () => {
small nitpick, the word "launch" should be changed to "launches"

2023-08-31 21:21 UTC, amauch-adobe commented on tests/milo/javis.feature.test.js
> +    await test.step('Validate the jarvis button launch the chat window', async () => {
both test steps are the exact same, one should be changed. My guess is it should be the first test step.  Probably the first step should be "'Navigate to page ', async () => {".

2023-08-31 21:21 UTC, amauch-adobe commented on tests/milo/javis.feature.test.js
> +      await page.waitForTimeout(6000);
I agree as well.

2023-08-31 21:21 UTC, amauch-adobe commented on tests/milo/javis.feature.test.js
> +      await page.waitForTimeout(6000);
same comment here from @JackySun9, its better to use waitForSelector.

2023-09-01 07:02 UTC, chadsunvice commented
Before starting the review, I am curious what value do these checks bring, as we already have all the Jarvis use cases tested [here](https://github.com/adobecom/nala/blob/main/tests/feds/jarvis.desktop.test.js). 

I see this as an overlap in logic. Also, the checks in the FEDS folder cover all the use cases, not just that the component loads. It interacts with it and checks it on Mobile landscape, and in different layouts, with different Jarvis configurations. 

This is the full-suite of use cases we already cover: [Sharepoint Jarvis Component](https://adobe.sharepoint.com/:f:/r/sites/adobecom/Shared%20Documents/milo/libs/feds/drafts/qa/[jarvis](https://adobe.sharepoint.com/:f:/r/sites/adobecom/Shared%20Documents/milo/libs/feds/drafts/qa/jarvis?csf=1&web=1&e=Y7Szwm)?csf=1&web=1&e=Y7Szwm).

I see @amauch-adobe has written the ticket. Why do we need these? Worst case, we can move the Jarvis checks already created under the Milo folder, if that is more akin to our regression strategy. But, I see this as an overlap in logic we already have covered.

2023-09-01 07:04 UTC, chadsunvice requested changes
Please see my comment in the main thread.

2023-09-01 07:38 UTC, narcis-radu commented
We can reuse the existing tests that @chadsunvice has created and move them to the Milo folder since the feature is part of Milo core. @sigadamvenkata, @amauch-adobe I see the JIRA ticket contains additional use-cases to be handled, like initialising and closing the chat conversation; maybe these tests should belong to chat core functionality, but feel free to enhance the existing chat integrations tests with additional use-cases.

2023-09-05 16:05 UTC, amauch-adobe commented
> Before starting the review, I am curious what value do these checks bring, as we already have all the Jarvis use cases tested [here](https://github.com/adobecom/nala/blob/main/tests/feds/jarvis.desktop.test.js).
> 
> I see this as an overlap in logic. Also, the checks in the FEDS folder cover all the use cases, not just that the component loads. It interacts with it and checks it on Mobile landscape, and in different layouts, with different Jarvis configurations.
> 
> This is the full-suite of use cases we already cover: [Sharepoint Jarvis Component](https://adobe.sharepoint.com/:f:/r/sites/adobecom/Shared%20Documents/milo/libs/feds/drafts/qa/%5Bjarvis%5D(https://adobe.sharepoint.com/:f:/r/sites/adobecom/Shared%20Documents/milo/libs/feds/drafts/qa/jarvis?csf=1&web=1&e=Y7Szwm)?csf=1&web=1&e=Y7Szwm).
> 
> I see @amauch-adobe has written the ticket. Why do we need these? Worst case, we can move the Jarvis checks already created under the Milo folder, if that is more akin to our regression strategy. But, I see this as an overlap in logic we already have covered.

@chadsunvice and @narcis-radu when I first created the ticket there wasn't anything yet made for the Jarvis chat.  Thanks for pointing the duplication out, I should have looked back in the PR history, that was my fault for not double-checking.  We certainly don't want to duplicate any work if the group feels like the test cases that were listed in the ticket should be added (and provide value to the testing), I say add them to the previous test(s) if that makes sense instead of creating a new test to maintain.  If they don't bring value, let's not create test cases to just create test cases.  As mentioned above, I created that ticket in the early stages of Jarvis development before functional use cases or test refinement were held.  It was a first crack at what might need to be tested.  For all things speaking the ticket might have just needed to be resolved when the first test(s) for Jarvis was made.

2023-09-06 06:09 UTC, narcis-radu commented
@amauch-adobe - no worries, I'm glad this has been cleared out. We'll make some changes in our tests to ensure all Milo core features and blocks are reflected in Nala.

2023-09-11 04:56 UTC, sigadamvenkata commented
since same feature AU available in feds nala folder we reuse it. hence closing this PR
@skumar09 @amauch-adobe @chadsunvice @JackySun9

2023-09-11 04:56 UTC, closed without merging