Add UI Screenshots for UAR
adobecom/nala pull request #164
Opened 2023-09-07 19:19 UTC by JackySun9

https://jira.corp.adobe.com/browse/MWPW-136147
1. take UI screenshots for UAR under desktop, tablet, mobile
2. upload them to wiki for review

https://wiki.corp.adobe.com/display/WEBT/UAR+UI+Screenshots

2023-09-07 19:52 UTC, amauch-adobe requested changes
See my comment about Viewport sizes.

2023-09-07 19:52 UTC, amauch-adobe commented on libs/webutil.js
> +    await this.page.setViewportSize({ width: 1920, height: 1080 });
Personal opinion here, I feel like this should be based on a config rather than hardcoded here in the webutil.js since maybe teams might have different viewport size requirements.  What does everyone else think? @skumar09 @chadsunvice @Dli3

2023-09-07 19:57 UTC, JackySun9 commented on libs/webutil.js
> +    await this.page.setViewportSize({ width: 1920, height: 1080 });
yes, we can do that, but I just have it here to make it work, if you have better idea, we can move it

2023-09-08 19:05 UTC, amauch-adobe commented on libs/webutil.js
> +    await this.page.setViewportSize({ width: 1920, height: 1080 });
A possible solution is you can add it to you uar.config.js file under the different chrome-live-desktop, safari-live-desktop, etc.

2023-09-11 23:01 UTC, JackySun9 commented on libs/webutil.js
> +    await this.page.setViewportSize({ width: 1920, height: 1080 });
@amauch-adobe I will your suggestion, but not put them into config, and put them into test, for my case, I just want to take screenshot for different resolution not going to run them on different devices

2023-09-11 23:12 UTC, amauch-adobe approved these changes
Approved.

2023-09-14 19:53 UTC, skumar09 approved these changes

2023-09-14 20:30 UTC, merged