MWPW-136264 : Blog URL redirects automation test script
adobecom/nala pull request #166
Opened 2023-09-09 09:42 UTC by skumar09

[MWPW-136264](https://jira.corp.adobe.com/browse/MWPW-136264): Blog URL redirects automation test script

PR includes 
- Automation test scripts for the following Blog redirect URLs

  -  Topic URL Redirects,
  -  Index URL Redirects,
  -  Author URL Redirects,
  -  Publish URL Redirects,

2023-09-11 19:43 UTC, amauch-adobe requested changes
Would it be best to make a generic URL redirect test that is one method but takes in a data file instead so the test can be used against many different sites instead of just blog.adobe.com?

2023-09-11 19:49 UTC, skumar09 commented
> Would it be best to make a generic URL redirect test that is one method but takes in a data file instead so the test can be used against many different sites instead of just blog.adobe.com?

@amauch-adobe: That makes sense, and redirect validation is a generic scenario across apps. Let me work on that. 
I need this PR to go through for any quick blog regression.

2023-09-12 17:08 UTC, JackySun9 commented on tests/blog/urlredirect.test.js
> +            await expect(page).toHaveURL(`${redirectBlogUrl}${redirectUrl}`);
you can use soft expect

2023-09-12 17:32 UTC, skumar09 commented on tests/blog/urlredirect.test.js
> +            await expect(page).toHaveURL(`${redirectBlogUrl}${redirectUrl}`);
@JackySun9: Yes, In this case, soft assertions are simple and a better choice than having a custom code to catch errors

2023-09-12 17:35 UTC, JackySun9 commented on tests/blog/urlredirect.test.js
> +          await expect(page).toHaveURL(`${redirectBlogUrl}${redirectUrl}`);
soft expect

2023-09-12 17:35 UTC, JackySun9 commented on tests/blog/urlredirect.test.js
> +          await expect(page).toHaveURL(`${redirectBlogUrl}${redirectUrl}`);
same here

2023-09-12 17:35 UTC, JackySun9 commented on tests/blog/urlredirect.test.js
> +          await expect(page).toHaveURL(`${redirectBlogUrl}${redirectUrl}`);
soft expect

2023-09-12 17:39 UTC, JackySun9 approved these changes

2023-09-12 18:08 UTC, merged