Add analytics test for UAR
adobecom/nala pull request #168
Opened 2023-09-14 21:49 UTC by JackySun9

1. add analytics test for UAR
2. move uar.js from libs to data/uar

2023-09-14 22:12 UTC, amauch-adobe requested changes
See my comment about the uar.js location.

2023-09-14 22:12 UTC, amauch-adobe commented on data/uar/quiz/uar.js
@JackySun9, I know you will laugh, but I started rethinking where you could put this file and thought it still makes sense to have it under the /libs directory. Maybe it would be good to create a subfolder under the libs directory called "uar", so move the uar.js to /libs/uar/uar.js.  What do you think @skumar09?

2023-09-14 22:12 UTC, amauch-adobe commented on tests/uar/quiz.dynamic.test.js
> +import { buildTestData } from '../../data/uar/quiz/uar.js';
obviously depending on @skumar09's approval of my comment above this line could potentially change to "../../libs/uar/uar.js"

2023-09-18 19:00 UTC, JackySun9 commented on data/uar/quiz/uar.js
I updated like you suggestion

2023-09-18 19:20 UTC, amauch-adobe approved these changes
Approved.

2023-09-18 21:32 UTC, skumar09 approved these changes

2023-09-18 21:36 UTC, merged