[MWPW-134804] Check placeholder formats
adobecom/nala pull request #171
Opened 2023-09-18 14:07 UTC by chadsunvice

Raised PR addresses Jira ticket **[MWPW-134804](https://jira.corp.adobe.com/browse/MWPW-134804) Ensure placeholders have the proper format**.

Automation tests should include placeholder availability checks, ensuring they exist and are in the proper format across Tier1 locales.

We're interested in both the default placeholders:
* Milo-specific placeholders: https://main--milo--adobecom.hlx.page/placeholders.json
* FEDS-specific placeholders: https://main--milo--adobecom.hlx.page/placeholders.json?sheet=feds

We need to check if entries from the data property of the JSON have key and value property names. Checking one element should be enough, as Franklin applies the pattern to all entries.

2023-09-18 17:07 UTC, amauch-adobe approved these changes
Approved.

2023-09-18 18:09 UTC, JackySun9 approved these changes

2023-09-18 20:23 UTC, skumar09 requested changes

2023-09-18 20:23 UTC, skumar09 commented on tests/feds/placeholders.test.js
> +  test.describe(`${features[0].name}`, () => {
Not sure if this is required :  `test.describe(`${features[0].name}`,

2023-09-19 10:11 UTC, chadsunvice commented on features/feds/placeholders.spec.js
> +      tags: '@milo @placeholders @milo-placeholders',
I agree, since we're testing these, they should only be in FEDS. Also, we're moving the main FEDS flows into Milo 
(GNAV components & misc)

2023-09-19 16:04 UTC, skumar09 approved these changes

2023-09-19 18:14 UTC, merged