commit helpx internal procedure component
adobecom/nala pull request #181
Opened 2023-10-05 07:03 UTC by ancysr

2023-10-05 08:16 UTC, sigadamvenkata reviewed
we need to check if there is any method in NALA to encode token since you are passing raw data for 'authtoken'

@skumar09 @amauch-adobe

2023-10-05 16:34 UTC, chadsunvice commented on features/helpx/procedure.spec.js
> +  };
Missing trailing newline at end of file.

2023-10-05 16:34 UTC, chadsunvice commented on selectors/helpx/procedure.selectors.js
> +
Extra trailing newline at the end of the file.

2023-10-05 16:34 UTC, chadsunvice commented on selectors/helpx/procedure.selectors.js
> +
Remove this empty newline.

2023-10-05 16:34 UTC, chadsunvice commented on tests/helpx/procedure.test.js
> +import {Procedure} from '../../selectors/helpx/procedure.selectors.js';
`{ Procedure }`

2023-10-05 16:34 UTC, chadsunvice commented on tests/helpx/procedure.test.js
> +
Reformat the spacing and remove unused code (commented). 

The `authToken` should be imported from an assets file.

2023-10-05 16:34 UTC, chadsunvice commented on tests/helpx/procedure.test.js
> +
Remove this extra newline.

2023-10-05 16:47 UTC, amauch-adobe commented on tests/helpx/procedure.test.js
> +  const authToken = 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ijdzb2k4N3pkb3NJRnc4b19fbVR5a082QlVRNEZBVGhjaHlyNGZqY1dSbWcifQ.eyJlbWFpbCI6ImhlbGl4QGFkb2JlLmNvbSIsIm5hbWUiOiJIZWxpeCBBZG1pbiIsImlhdCI6MTY4OTkyNjExMiw
Add a GitHub Environment Secret here on the Nala Repo as well as any other repo that will run these tests, so in this case probably Milo's repo.  That way it will be passed as an environment variable name and will not be exposed to anyone publicly.  If you run it locally you will just need to add an environment variable to the command prompt/terminal that coincides with the name of the variable.  If you run it locally in VS Code you will just need to first add the environment variable to your user profile on the system and then restart VS Code and it will pick it up for the test executions.

Reference:  https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository

In Nala's repository reference: nala/libs/imslogin.js

![Screenshot 2023-10-05 at 10 46 30 AM](https://github.com/adobecom/nala/assets/56042473/acd45954-18ef-4477-bc35-019be995a4e4)

cc @sigadamvenkata

2023-10-05 16:48 UTC, amauch-adobe commented on tests/helpx/procedure.test.js
> +   //const url = "https://helpx-internal.stage.adobe.com/automation/blocks/procedure.html";
small nit-pick, does this commented-out variable need to stay here?

2023-10-05 16:49 UTC, amauch-adobe commented on tests/helpx/procedure.test.js
> +      //await page.goto(`${baseURL}${features[0].path}`);
same thing here, do these commented-out code lines need to remain?

2023-10-05 16:55 UTC, amauch-adobe requested changes

2023-10-05 16:55 UTC, amauch-adobe commented on envs/envs.js
> +  '@helpxInternal_live':'https://helpx-internal.stage.adobe.com',
Does this url proxy from the hlx.page environment endings?  If so we are not to use urls that pull/proxy from hlx.page in automation since it will tax Franklin's Fastly CDN, which we will get flagged for.  hlx.live or production urls are what is possible for regression/iterated test cases.

2023-10-05 17:12 UTC, amauch-adobe commented on tests/helpx/procedure.test.js
> +  const authToken = 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ijdzb2k4N3pkb3NJRnc4b19fbVR5a082QlVRNEZBVGhjaHlyNGZqY1dSbWcifQ.eyJlbWFpbCI6ImhlbGl4QGFkb2JlLmNvbSIsIm5hbWUiOiJIZWxpeCBBZG1pbiIsImlhdCI6MTY4OTkyNjExMiw
Also you will need to add the variables into the github action workflows to have the values passed through to the test.  As shown here in the .yaml files under the .github/workflows directory for both Milo/Nala's repo.
 
 
![Screenshot 2023-10-05 at 11 09 44 AM](https://github.com/adobecom/nala/assets/56042473/1b8e9829-e6e5-48e2-acfc-689c1958e797)

The files needing to be updated will be daily.yml, debug.yml, manual.yml, self.yml in Nala under the "env:" section.
The file needing to be updated in Milo will be run-nala.yml under the "env:" section.

2023-10-12 04:44 UTC, ancysr commented on envs/envs.js
> +  '@helpxInternal_live':'https://helpx-internal.stage.adobe.com',
It has hlx.live;  stage--helpx-internal--adobecom.hlx.live

2023-10-12 04:45 UTC, ancysr commented on features/helpx/procedure.spec.js
> +  };
done

2023-10-12 04:46 UTC, ancysr commented on selectors/helpx/procedure.selectors.js
> +
done

2023-10-12 04:47 UTC, ancysr commented on selectors/helpx/procedure.selectors.js
> +
removed

2023-10-12 04:48 UTC, ancysr commented on tests/helpx/procedure.test.js
> +import {Procedure} from '../../selectors/helpx/procedure.selectors.js';
added space

2023-10-12 05:14 UTC, ancysr commented on tests/helpx/procedure.test.js
> +  const authToken = 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ijdzb2k4N3pkb3NJRnc4b19fbVR5a082QlVRNEZBVGhjaHlyNGZqY1dSbWcifQ.eyJlbWFpbCI6ImhlbGl4QGFkb2JlLmNvbSIsIm5hbWUiOiJIZWxpeCBBZG1pbiIsImlhdCI6MTY4OTkyNjExMiw
- Added secret key under https://github.com/ancysr/nala/settings/secrets/actions
- Files daily.yml, debug.yml, manual.yml, self.yml updated.

2023-10-12 05:16 UTC, ancysr commented on tests/helpx/procedure.test.js
> +
removed

2023-10-12 05:41 UTC, ancysr commented on tests/helpx/procedure.test.js
> +      //await page.goto(`${baseURL}${features[0].path}`);
removed the commented out lines

2023-10-12 05:45 UTC, ancysr commented on tests/helpx/procedure.test.js
> +
Removed unused code.
authToken is now set as an environmental variable.

2023-10-12 05:45 UTC, ancysr commented on tests/helpx/procedure.test.js
> +   //const url = "https://helpx-internal.stage.adobe.com/automation/blocks/procedure.html";
removed

2023-10-12 21:06 UTC, amauch-adobe requested changes
Just a recommendation to add a check for the authToken variable to ensure it is not empty/blank.  See my comments.

2023-10-12 21:06 UTC, amauch-adobe commented on tests/helpx/beforeafter.test.js
> +  const authToken = process.env.HLX_TKN;
I would add a check here to verify that the authToken isn't empty/blank, then provide an output so that the runner log may provide context to the failure of the test.  There is a possibility for the environment secret to accidentally be removed or something else, it's just good practice.

2023-10-12 21:06 UTC, amauch-adobe commented on tests/helpx/procedure.test.js
> +  const authToken = process.env.HLX_TKN;
Same case here, have a check to ensure the authToken variable is not empty/blank.

2023-10-16 05:59 UTC, sigadamvenkata approved these changes

2023-10-16 10:10 UTC, ancysr commented on tests/helpx/beforeafter.test.js
> +  const authToken = process.env.HLX_TKN;
Added the check to verify that auth token is set and not empty

2023-10-16 10:10 UTC, ancysr commented on tests/helpx/procedure.test.js
> +  const authToken = process.env.HLX_TKN;
Added the check to verify that auth token is set and not empty

2023-10-16 16:57 UTC, skumar09 approved these changes
@ancysr : All looks good, 
Note: Please remove the extra space or eof maker in some pages  

@sigadamvenkata

2023-10-16 17:42 UTC, amauch-adobe approved these changes
@skumar09 we will need to add a repository secret in the Milo repository and the Nala repository for the auth token before or immediately after this test has been merged.  Preferably before, otherwise the test will fail on PRs and daily regression runs.

2023-10-16 17:46 UTC, skumar09 commented
> @skumar09 we will need to add a repository secret in the Milo repository and the Nala repository for the auth token before or immediately after this test has been merged. Preferably before, otherwise the test will fail on PRs and daily regression runs.

@amauch-adobe : I have already created/added to the Nala repo. , for Milo repo, I think we don't need at the moment, ( will discuss with you on the approach to handle from Nala repo.)

2023-10-17 16:15 UTC, merged