MWPW-137960 : Refactor Marquee block test cases, and other improvments
adobecom/nala pull request #185
Opened 2023-10-17 04:13 UTC by skumar09

[MWPW-137960](https://jira.corp.adobe.com/browse/MWPW-137960): Refactor Marquee block test cases 

PR includes

- Refactoring of Marquee block test cases
- Introducing style folder to read `variables.css` and` block.css` files to verify CSS / attributes 
   - Note: This is a bit of experiment and exploration, currently including both files under the styles folder; we won't be having this folder and files when we move test cases to the corresponding repository 
- Introducing visual comparison step at section/block level.
   - Note: This is also a bit of experiment and exploration to evaluate execution time with visual comparision
- Introducing validation for console log errors 
```
-     await test.step('step-3: Verify and log if any console errors', async () => {
      consoleErrors.length > 0 && console.log('[Console error]:', consoleErrors);      
      expect.soft(consoleErrors.length).toBe(0);      
    });
```

2023-10-17 15:55 UTC, amauch-adobe requested changes
See my small comments.  My biggest question/comment is what is our plan for housing these images.  I know this was mostly for experimentation, but I don't think we want to load up the Nala repo with "golden/base" images for comparison tests.  The same is for result images that are taken.  The original concept for saving images for Nala was to have a separate repository to house images that we could just pull down for the comparison tests.  I had already created a repo for this named [nala-screenshots](https://github.com/adobecom/nala-screenshots).  This recommendation came from this community [discussion](https://github.com/orgs/adobecom/discussions/561).

2023-10-17 15:55 UTC, amauch-adobe commented on libs/cssparser.js
> +  const parsedBlockCSS = css.parse(blcokCSSContent);
misspelled blockCSSContent, it is currently blcokCSSContent.

2023-10-17 15:55 UTC, amauch-adobe commented on libs/cssparser.js
> +export function getCSSObjects(variableCSSContent, blcokCSSContent) {
misspelled blockCSSContent, it is currently blcokCSSContent.

2023-10-17 15:55 UTC, amauch-adobe commented on libs/webutil.js
> +          //console.log('property : ', property ,'::', expectedValue);
was this a debug/testing log statement that is no longer needed or should it be uncommented?

2023-11-09 01:38 UTC, closed without merging

2023-11-09 01:38 UTC, skumar09 commented
Closing this PR, (updates are made as part of other pr's )