CodeBlock and Draft
adobecom/nala pull request #196
Opened 2023-10-27 06:19 UTC by ancysr

2023-10-27 07:01 UTC, skumar09 requested changes
@ancysr : Overall PR is decent; please update the review comments
- Update pom classes to `default class`

2023-10-27 17:34 UTC, amauch-adobe requested changes
Really good test, and a great job!  See my comments below.

2023-10-27 17:34 UTC, amauch-adobe commented on features/helpx/codeBlock.spec.js
> +      envs: '@helpxInternal_live',
I agree with @skumar09 we don't need envs key/value pair anymore.  The documentation for the Nala Wiki needs to be updated, I'll make a ticket.

2023-10-27 17:34 UTC, amauch-adobe commented on selectors/helpx/codeBlock.selectors.js
> +exports.CodeBlock = class CodeBlock {
please update the following for all POM files

- update to default class
- file name to .page.js (once again the Nala Wiki documentation needs to be updated to reflect these changes)

2023-10-27 17:34 UTC, amauch-adobe commented on selectors/helpx/draft.selectors.js
> +
small personal opinion, feel free to make the change or not, but I like removing extra whitespace when it is not needed.  So if it was me I would remove the extra lines between the curly braces.

2023-10-27 17:34 UTC, amauch-adobe commented on tests/helpx/draft.test.js
> +    // Check procedure present
maybe not necessary for the comments here on the toBeVisible() checks since the code itself answers that question.  Just a personal preference though.

2023-10-30 09:15 UTC, ancysr commented on features/helpx/beforeAfter.spec.js
> +      envs: '@helpxInternal_live',
This environment is for helpx internal pages. We will need for helpx external pages as well in future.

2023-10-30 09:16 UTC, ancysr commented on selectors/helpx/draft.selectors.js
> +exports.Draft = class Draft {
done

2023-10-30 09:43 UTC, ancysr commented on selectors/helpx/procedure.selectors.js
> +  };
done

2023-10-30 09:43 UTC, ancysr commented on tests/helpx/codeBlock.test.js
> +    console.info(`[CodeBlock] Checking page: ${baseURL}${features[0].path}`);
done

2023-10-30 09:43 UTC, ancysr commented on tests/helpx/codeBlock.test.js
> +    // Check as3 codeBlock present
done

2023-10-30 09:43 UTC, ancysr commented on tests/helpx/draft.test.js
> +     // Set the authorization token in the header
done

2023-10-30 09:45 UTC, ancysr commented on selectors/helpx/procedure.selectors.js
> +      // Procedure Selectors:
not clear on the review comment

2023-10-31 04:41 UTC, ancysr commented on selectors/helpx/codeBlock.selectors.js
> +exports.CodeBlock = class CodeBlock {
changes made

2023-10-31 04:51 UTC, skumar09 commented on configs/helpx.config.js
> +    ? [['github'], ['../utils/reporters/json-reporter.js'], ['../utils/reporters/json-reporter.js']]
pls change` json-reporter.js to bse-reporter.js ` ( pls refer the milo-automation slack channel)

2023-10-31 05:04 UTC, skumar09 approved these changes
- Please update `env / baseURL` related comments
- The rest all looks good
- Approving...

2023-10-31 06:33 UTC, ancysr commented on configs/helpx.config.js
> +    baseURL: process.env.BASE_URL || envs['@helpxInternal_live'] || 'https://helpx-internal.stage.adobe.com',
Made the changes as suggested

2023-10-31 06:34 UTC, ancysr commented on configs/helpx.config.js
> +    ? [['github'], ['../utils/reporters/json-reporter.js'], ['../utils/reporters/json-reporter.js']]
done

2023-10-31 06:35 UTC, ancysr commented on tests/helpx/draft.test.js
> +    // Check procedure present
sure, will consider for all future PRs

2023-10-31 06:37 UTC, ancysr commented on selectors/helpx/draft.selectors.js
> +
Sure, have tried removing the extra spaces on the files. Will take care of this in future PRs.

2023-10-31 06:38 UTC, ancysr commented on features/helpx/codeBlock.spec.js
> +      envs: '@helpxInternal_live',
made the changes

2023-10-31 06:38 UTC, ancysr commented on features/helpx/beforeAfter.spec.js
> +      envs: '@helpxInternal_live',
removed

2023-10-31 15:45 UTC, amauch-adobe approved these changes
Approved.

2023-10-31 16:35 UTC, JackySun9 commented
Just want to know where to set this "process.env.HLX_TKN"

2023-10-31 17:38 UTC, amauch-adobe commented
> Just want to know where to set this "process.env.HLX_TKN"

If you are running locally you will need to add HLX_TKN as an environment variable with the token value to your terminal/command prompt profile.  If you are running it in GitHub Actions/CI you will need to add a Repository Secret named HLX_TKN with the value.  @ancysr will have the token value.

2023-11-02 06:21 UTC, merged