[MWPW-139314] : Action-item Block tests scripts
adobecom/nala pull request #208
Opened 2023-11-15 22:37 UTC by skumar09

[MWPW-139314](https://jira.corp.adobe.com/browse/MWPW-139314 ): Action-item Block tests scripts

PR includes 
- Automation test scripts for the following features of the Action-item block

   - Action-item (small)
   - Action-item (medium)
   - Action-item (large)
   - Action-item (center)
   - Action-item (rounded)
   - Action-item (float button)
   - Action-item (scroller)
   - Action-item (scroller with navigation)

2023-11-15 22:53 UTC, amauch-adobe approved these changes
Approved, but see my small recommendation.

2023-11-15 22:53 UTC, amauch-adobe commented on global.setup.js
> +    console.info('---- Running Tests in the GitHub ---------');
to follow same text construct probably should say "----Running Test in the GitHub environment --------'

2023-11-15 23:13 UTC, Dli3 commented on .github/workflows/debug.yml
> +          reporter: html
Extra space here. @skumar09

2023-11-16 00:54 UTC, JackySun9 requested changes

2023-11-16 00:54 UTC, JackySun9 commented on selectors/milo/actionitem.block.page.js
> +  constructor(page, type, nth = 0) {
no use for type

2023-11-16 00:54 UTC, JackySun9 commented on selectors/milo/actionitem.block.page.js
> +    this.image = this.mainImage.locator('img').nth(0);
0 or nth?

2023-11-16 00:54 UTC, JackySun9 commented on utils/reporters/base-reporter.js
> +      runUrl = `https://app.circleci.com/pipelines/github/wcms/nala/10/workflows/${workflowId}/jobs/${jobNumber}`;
is this URL correct?

2023-11-16 01:04 UTC, skumar09 commented on selectors/milo/actionitem.block.page.js
> +    this.image = this.mainImage.locator('img').nth(0);
it's 0 ( not nth for img)

2023-11-16 01:08 UTC, skumar09 commented on utils/reporters/base-reporter.js
> +      runUrl = `https://app.circleci.com/pipelines/github/wcms/nala/10/workflows/${workflowId}/jobs/${jobNumber}`;
- good catch, (updated the URL...)
-

2023-11-16 01:09 UTC, JackySun9 approved these changes

2023-11-16 08:54 UTC, merged