PR for Offer selector Tool test cases which cover given use cases
adobecom/nala pull request #214
Opened 2023-11-21 10:26 UTC by sigadamvenkata

PR for Offer selector Tool test cases which cover below use cases
US , JP CC prices
Currency formats
Student and teacher Edition prices
Strike through price
CC / LR / PS month & year subscription prices
UCV3 check out formats (email, segmentation etc)

Jira: https://jira.corp.adobe.com/browse/MWPW-135460

Result run in local:
![OST-consolidated-result](https://github.com/adobecom/nala/assets/130433161/390dff1f-2f6f-490e-9851-ea849615f926)

2023-11-21 17:52 UTC, JackySun9 requested changes

2023-11-21 17:52 UTC, JackySun9 commented on features/cc/ostprices.spec.js
> +      envs: '@cc_live @adobe_stage',
I think you don't need envs here, same to others

2023-11-21 17:52 UTC, JackySun9 commented on selectors/cc/ostprices.page.js
> +    this.productname = page.locator('//em[text()="Creative cloud all apps :"]');
for locator, try to use id, css or xpath first, if not working, use less text, because they are often changing, then you need to update your test

2023-11-21 22:17 UTC, skumar09 commented on selectors/cc/ostprices.page.js
> +    this.productname = page.locator('//em[text()="Creative cloud all apps :"]');
@sigadamvenkata : I agree with @JackySun9 , please update the locators

2023-11-21 22:19 UTC, skumar09 requested changes

2023-11-21 22:19 UTC, skumar09 commented on selectors/cc/ostprices.page.js
> +    this.jpproductprice = page.locator('//span[@aria-label="10,280 &#20870; 毎月 ライセンスごと"]');
please avoid using hard-coded text in locators,

2023-11-22 07:42 UTC, amauch-adobe requested changes
See comments through-out well done on the test, just a few things.  I also agree with the other reviewers' comments.

2023-11-22 07:42 UTC, amauch-adobe commented on features/cc/ostprices.spec.js
> +      envs: '@cc_live @adobe_stage',
yup, envs is no longer needed where there are separate <app>.config.js for each app being tested through Nala, i.e. milo.config.js.  These config files contain which environment path to use.

2023-11-22 07:42 UTC, amauch-adobe commented on selectors/cc/ostprices.page.js
> +    // Student teccher edition price checks
'teccher' is misspelt should be teacher.

2023-11-22 07:42 UTC, amauch-adobe commented on selectors/cc/ostprices.page.js
> +    // page has card layout with month , year prices and CTAs
extra space between comma should be removed.

2023-11-22 07:42 UTC, amauch-adobe commented on tests/cc/ostprices.test.js
> +  ost = new Ostprices(page);
missing indent

2023-11-22 07:42 UTC, amauch-adobe commented on tests/cc/ostprices.test.js
> +    });
curly brace and parens should be aligned with the 'test' method signature and not with the child statements within the method.  This should be updated throughout the file.

2023-11-22 07:42 UTC, amauch-adobe commented on tests/cc/ostprices.test.js
> +  await page.locator('//a[@daa-ll="Buy now-1|Make Create Amazing"]').click();
I believe this locator string should be in the page.js file and not exposed in the test.  This should be updated throughout the test file.

2023-11-22 07:42 UTC, amauch-adobe commented on tests/cc/ostprices.test.js
> + await test.step('Verify the month and year price display , CTA for UCv3 segment checkout destination', async () => {
full test.step method should be indented to be clear that it belongs to the test() method above it.  This should be applied throughout the test file.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + page.waitForLoadState();
Apart from what others spotted, I'd add you will need to add `await` to make sure the promise of `waitForLoadState` is met, before doing other actions. 

Also, if you don't explicitly specify the `domcontentloaded`, or `networkidle` params, Playwright defaults to `load` state, which is triggered when a page starts loading the assets, which in turn might not be enough to have your expected content loaded/visible/intractable.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> +});
Formatting is off on this test file. Make sure it respects the formatting of the other test files from NALA.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> +});
Formatting is off on this test file. Make sure it respects the formatting of the other test files from NALA.

2023-11-22 09:41 UTC, chadsunvice commented on selectors/cc/ostprices.page.js
> +    this.ps_priceyear_jp = page.locator('//span[@aria-label="28,776 &#20870; 毎年 ライセンスごと"]');
You might want to switch to camelCase convention for naming of selectors, which @skumar09 was adamant about and tries to push in hopes of consistency with the rest of the teams.

eg: `this.ps_pricebeforedelimiter` becomes `psPriceBeforeDelimiter`
eg: `productname_2` becomes `productName2`
etc.

2023-11-22 09:41 UTC, chadsunvice commented on tests/cc/ostprices.test.js
> + await expect(page).toHaveURL(new RegExp('co=JP&lang=ja'));
I think it is overkill to use RegExp for this assertion, you can also use `expect(await page.url()).toContain('<substring>')`.

2023-11-30 17:41 UTC, amauch-adobe approved these changes
Approved

2023-12-01 16:06 UTC, merged