Helpx_Milo Components Script Fixes
adobecom/nala pull request #235
Opened 2023-12-18 17:12 UTC by kirupacommit

2023-12-23 13:55 UTC, chadsunvice approved these changes

2024-01-03 18:02 UTC, JackySun9 commented on configs/helpx.config.js
> -    ? [['github'], ['list'], ['../utils/reporters/base-reporter.js']]
You need to add base-reporter.js

2024-01-04 03:19 UTC, kirupacommit commented on configs/helpx.config.js
> -    ? [['github'], ['list'], ['../utils/reporters/base-reporter.js']]
@JackySun9 I appreciate your comments. Added Base Reporter along with https://github.com/adobecom/nala/pull/235/commits/d5eb7a1dff28aa4539a71dfd4a3ea358c9ff4e31.
![image](https://github.com/adobecom/nala/assets/94790097/ec958921-e5b8-4e7f-acd7-a586f24da0ea)

2024-01-04 20:18 UTC, JackySun9 commented on features/helpx/draft.spec.js
> +      path: '/automation/blocks/Draft/draft-test.html',
Is this correct?

2024-01-04 21:16 UTC, skumar09 commented
@kirupacommit : Helpx daily run is failing because of the test title 

![image](https://github.com/adobecom/nala/assets/22153717/678c903a-9a73-45b4-9448-5601890dc5cf)

**Your test title does not have name and tag information.** 

![image](https://github.com/adobecom/nala/assets/22153717/0e147aa9-6340-4dfd-9ef1-dfeeb4a52393)

**Please refer to the Nala test template** 

![image](https://github.com/adobecom/nala/assets/22153717/d875663b-a51b-4da3-a97f-4e2d0530a6a2)

The `test title` should contain the `test name` and `tag` pieces of information that are defined in the corresponding `.spec.js`

![image](https://github.com/adobecom/nala/assets/22153717/5d1e9660-29c3-441f-8f0d-a8f72ef588eb)

2024-01-04 21:19 UTC, skumar09 requested changes

2024-01-05 05:39 UTC, kirupacommit commented on features/helpx/draft.spec.js
> +      path: '/automation/blocks/Draft/draft-test.html',
Yes, Recently I made some folder changes.
![image](https://github.com/adobecom/nala/assets/94790097/208b6bf4-a3f8-43f9-81a2-d456448f5f7f)

2024-01-05 10:17 UTC, kirupacommit commented on configs/helpx.config.js
> -    ? [['github'], ['list'], ['../utils/reporters/base-reporter.js']]
Now i have added Base reporter to the helpx Project

2024-01-05 10:18 UTC, kirupacommit commented on configs/helpx.config.js
> +export default helpxconfig;
Thought of giving project specific config name so used helpxconfig, since other libs are using config i have changed to default config.

2024-01-05 10:19 UTC, kirupacommit commented
@skumar09 Thanks for your insight on the Github Actions , Now i have renamed the test cases and triggered the jobs as well. Thank You!

2024-01-05 22:07 UTC, skumar09 commented
@kirupacommit :
- Approving the PR, all looks good. Thanks for the discussion and adding dailyrun.yaml. for Helpx, please start monitoring the slack channel: `milo-automation-dev` for daily run results.
- Please update the few locators in a better way ( refer to `procedure` pom file )

2024-01-05 22:07 UTC, skumar09 approved these changes

2024-01-05 22:07 UTC, skumar09 commented on selectors/helpx/procedure.page.js
> +    this.noteiconinprocedure = page.locator("//div[contains(@daa-lh,'b11|procedure|nopzn|nopzn')]/ol/li[6]/child::div/child::div[contains(@class,'note alert')]/span[contains(@class,'note-icon')]");
- I would not suggest using such a lengthy locator ( i.e., Xpath)
- Playwright provides plenty of other better options; please try using better selectors like CSS ( please refer to playwright locators [https://playwright.dev/docs/locators#locating-elements]
- `daa-lh,'b11|procedure|nopzn|nopzn` are personalization attributes

2024-01-08 05:52 UTC, skumar09 approved these changes

2024-01-08 05:53 UTC, merged