Helpx Note Text Component
adobecom/nala pull request #258
Opened 2024-01-31 11:08 UTC by kirupacommit

![image](https://github.com/adobecom/nala/assets/94790097/50945ee3-9438-490a-a7ca-2303e8a69c34)

2024-01-31 20:58 UTC, amauch-adobe commented
@kirupacommit, quick question is there a ticket or a brief summary that can be given to help us know what is expected in this test PR?  It helps me when I'm reviewing to get a general insight of what to look for.

2024-01-31 21:16 UTC, JackySun9 commented on selectors/helpx/noteText.page.js
> +    this.b1textComponentNoteStyle = page.locator("//div[contains(@daa-lh,'b1|note|nopzn|nopzn')][contains(@class,'note note')]");
can you use css locators?

2024-01-31 21:50 UTC, amauch-adobe requested changes
@kirupacommit,
See my changes.

2024-01-31 21:50 UTC, amauch-adobe commented on selectors/helpx/noteText.page.js
> +    // https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B037AABF8-973C-4402-89EC-8E176F463B34%7D&file=Note_component.docx&action=default&mobileredirect=true
not a big deal, but just curious if these commented out urls are still needed.  If not, I would recommend removing them.  Just a small nit pick, though.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
usually we wait for the loadstate "domcontentloaded" so that all JavaScript elements are loaded.  @skumar09 can correct me if I'm wrong.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
This helps to ensure all elements in the DOM are loaded since network idle might have a false positive in starting before all the DOM is loaded due to the network on a machine just having a spurt moment of idling.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
same case here, might want to choose "domcontentloaded" instead of networkidle.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
same case here, might want to choose "domcontentloaded" instead of networkidle.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
same case here, might want to choose "domcontentloaded" instead of networkidle.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
same case here, might want to choose "domcontentloaded" instead of networkidle.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
same case here, might want to choose "domcontentloaded" instead of networkidle.

2024-01-31 21:50 UTC, amauch-adobe commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
same case here, might want to choose "domcontentloaded" instead of networkidle.

2024-02-01 13:50 UTC, kirupacommit commented
> @kirupacommit, quick question is there a ticket or a brief summary that can be given to help us know what is expected in this test PR? It helps me when I'm reviewing to get a general insight of what to look for.

sure. Here's the ticket : https://jira.corp.adobe.com/browse/MWPW-122844

2024-02-01 13:52 UTC, kirupacommit commented on selectors/helpx/noteText.page.js
> +    this.b1textComponentNoteStyle = page.locator("//div[contains(@daa-lh,'b1|note|nopzn|nopzn')][contains(@class,'note note')]");
Hi jacky, I appreciate your comment. With the current Xpaths the test cases are passing good. why specific to css locators? because it will be rework.

2024-02-01 13:53 UTC, kirupacommit commented on selectors/helpx/noteText.page.js
> +    // https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B037AABF8-973C-4402-89EC-8E176F463B34%7D&file=Note_component.docx&action=default&mobileredirect=true
I had it for my reference. with the updated PR removed . Thanks for noticing https://github.com/adobecom/nala/pull/258/commits/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:54 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/pull/258/commits/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:54 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/commit/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:54 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/commit/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:54 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/commit/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:54 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/commit/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:55 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/commit/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-01 13:55 UTC, kirupacommit commented on tests/helpx/noteText.test.js
> +    await page.waitForLoadState('networkidle');
Update the code with domcontentloaded on my latest PR https://github.com/adobecom/nala/commit/15bb8b6f8021a0168fe39cf4afa724622fdd9c28

2024-02-06 09:23 UTC, kirupacommit commented
@amauch-adobe @JackySun9 @skumar09 Can you please review above PR with latest Changes?

2024-02-06 16:18 UTC, skumar09 approved these changes
Looks good.

2024-02-06 16:33 UTC, amauch-adobe approved these changes
Approved.

2024-02-06 16:46 UTC, merged

2024-02-06 16:48 UTC, amauch-adobe commented
@kirupacommit, it might be good for you to sign the Adobe CLA as shown below so that the check passes for future PRs.  Also just a comment on usage of XPath, you are correct it works and is an available option for finding elements within Playwright.  I believe a reason for why Jacky asked you about it is because XPath isn't as reliable/resilient/stable when finding elements in Playwright as other specific defined element finders provided from Playwright as stated here in Playwright's [documentation](https://playwright.dev/docs/locators#locate-by-css-or-xpath).  My usual recommendation is use the more stable/resilient element finders always, and if it can't find or work with the needs of the test look to XPath or CSS Selector strings.  Just something to keep in mind, take it or leave it.  :)