Adding browserstack config
adobecom/nala pull request #278
Opened 2024-03-01 01:14 UTC by Dli3

Ticket: [MWPW-122014](https://jira.corp.adobe.com/browse/MWPW-122014) 

- Adding Browserstack config so we can run tests against the available device and OS options in browserstack through their Browserstack SDK ([Their recommended approach as the other option is now legacy](https://www.browserstack.com/docs/automate/playwright/getting-started/nodejs/integrate-your-tests-sdk))
- As per their support, we needed playwright version 1.38.1 or higher. This PR updated our version to 1.38.1 and will need each team to verify that there are no issues caused by this for them.
- [iOS and Android isn't supported at this time.](https://www.browserstack.com/docs/automate/playwright/browsers-and-os) Will add those when the option is available. The documentation specifies that version 1.38.1 has Android chrome as an option but I couldn't get it to work. I've reached out to support and will update the yml file when I can get it working.

How to run your test in Browserstack:
1. Install the dependencies. 
2. Set up your BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY env variables.
3. Command: `npx browserstack-node-sdk playwright test --config='./configs/<project>.config.js'`.

2024-03-01 05:44 UTC, JackySun9 commented
did you run all the tests for this?

2024-03-01 06:59 UTC, kirupacommit commented
Hi jacky,

My Test cases are failing due to environment variable changes. So to debug
the issue , I ran the test cases.

May be i will run one more time if fix is merged

On Fri, 1 Mar 2024 at 11:14, Jacky Sun ***@***.***> wrote:

> did you run all the tests for this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adobecom/nala/pull/278#issuecomment-1972551897>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWTGDUJ55RGUHAGOCVQ4GMLYWAIVDAVCNFSM6AAAAABEA5VWKOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZSGU2TCOBZG4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-03-01 19:03 UTC, Dli3 commented
> did you run all the tests for this?

Yes, I ran all the tests on the bstack branch vs main. I didn't see any issues with the update. There are failures with some of the tests, but I confirmed that it was happening on the main branch as well.

2024-03-01 19:18 UTC, JackySun9 approved these changes

2024-03-01 20:10 UTC, amauch-adobe requested changes
See my questions, comments.  Looks great Dennis, excellent job.

2024-03-01 20:10 UTC, amauch-adobe commented on browserstack.yml
> +    browserVersion: latest
2 quick questions. 

1. Is there a reason to have Monterey, Ventura, and Sonoma instead of just the latest Mac OSX listed since my guess is this is a template for teams to adjust as needed for their own needs?  
2. I noticed Firefox doesn't get configs for Sonoma or Monterey, is there a reason for this?

2024-03-01 20:10 UTC, amauch-adobe commented on browserstack.yml
> +browserstackLocal: true # <boolean> (Default false)
would it be better to leave this value "browserstackLocal" as false?  The reason I say that is if this is to be used as a template for teams it would make more sense to have values at their defaults unless it is absolutely necessary for all executions/runs/setups regardless of project being tested.

2024-03-01 20:10 UTC, amauch-adobe commented on package.json
> +    "test:bstack-acom": "npx browserstack-node-sdk playwright test --config='./configs/acom.config.js'",
Its entirely up to you, this is just a personal opinion, but if --config can be something sent in as a parameter on the command line execution, I feel it would be best to limit the named npm execution commands to just the bare minimum to run it.  Then users can just add the config parameter themselves and the package.json file is cleaner and not so large with multiple command paths.

2024-03-01 20:31 UTC, Dli3 commented on browserstack.yml
> +browserstackLocal: true # <boolean> (Default false)
Thanks I changed it when I was testing this and missed changing it back. I updated it back to false.

2024-03-02 00:15 UTC, Dli3 commented on package.json
> +    "test:bstack-acom": "npx browserstack-node-sdk playwright test --config='./configs/acom.config.js'",
> Its entirely up to you, this is just a personal opinion, but if --config can be something sent in as a parameter on the command line execution, I feel it would be best to limit the named npm execution commands to just the bare minimum to run it. Then users can just add the config parameter themselves and the package.json file is cleaner and not so large with multiple command paths.

That's a good point. I've removed the added lines and left test:bstack.

2024-03-02 00:17 UTC, Dli3 commented on browserstack.yml
> +    browserVersion: latest
I thought it would be useful to add Monterey and Ventura when Safari becomes available since we test two versions back. But since that's not available yet, I've removed the other versions and kept Ventura. 

I've added Firefox on Mac Ventura. 

Thanks!

2024-03-02 04:29 UTC, amauch-adobe approved these changes
Approved.

2024-03-08 22:55 UTC, Dli3 commented
Closing PR to fix a workflow issue. I'll open another PR.

2024-03-08 22:55 UTC, closed without merging