Nala base reporter CircleCi url update
adobecom/nala pull request #285
Opened 2024-03-06 07:11 UTC by amauch-adobe

updated circleci link for nala test results report printout.

2024-03-06 22:36 UTC, Dli3 approved these changes
Looks like there's a few linter errors.

2024-03-06 22:41 UTC, JackySun9 requested changes
Can you fix eslint errors?

2024-03-06 22:41 UTC, JackySun9 commented on utils/reporters/base-reporter.js
>  import { sendSlackMessage } from '../../libs/slack.js';
what's this?

2024-03-07 20:19 UTC, JackySun9 approved these changes

2024-03-07 20:46 UTC, amauch-adobe commented
@JackySun9 , the slack library is used to send the JSON payload to slack webhook for nala test results (#nala-test-results slack channel).

Where I had only made the change to the file to update the circleci url text for the base reporter, I wasn't planning on addressing all of the Lint errors.  I think it would be good for us to create a ticket in the Jira Epic to audit all of the files using the Linter so that we can fix previous files that are already in the repository.  @skumar09 what do you think.

2024-03-07 20:46 UTC, merged