Adding modal tests
adobecom/nala pull request #33
Opened 2022-11-11 22:40 UTC by Dli3

Adding modal tests.
Ticket: [https://jira.corp.adobe.com/browse/MWPW-119063](url)

The tests will verify the following:

- selecting a modal button will open a modal with a hash in url
- selecting the modal close button closes the modal and hash gets removed in url
- the modal is within viewport when opened 
- the first focus item is the close button when modal opens
- able to close modal with the escape key

2022-11-14 18:10 UTC, amauch-adobe requested changes
This is awesome, Dennis!  You did a really good job, I had a few comments and potential requested changes.  Please feel free to answer my questions back in the PR.

2022-11-14 18:10 UTC, amauch-adobe commented on tests/modal.test.js
> +      if (page._parent._browserType._initializer.name === 'webkit') {
As another option for returning the browser type you can send in the "browser" object at the test method declaration like so:  

test(props.title, async ({ page, browser }) => {

And then you can make a conditional as such:

browser.browserType().name() === 'chromium'

There isn't a right or wrong way to do it, it is just another way.  No need to make a change, just pointing out another option.

2022-11-14 18:10 UTC, amauch-adobe commented on tests/modal.test.js
> +        while (page.url().includes('#') && count < 10) {
Question for clarification:  

Where you said it takes four tabs to get the escape key option to work for webkit to close a modal, why is the loop going 10 iterations?  Is it just an arbitrary number to ensure you eventually get to the other condition of the page not including the '#' mark?  Is there a need for the arbitrary 10, if it is arbitrary?  Why not 6?  Just curious, I'm sure you have reason, I was just wondering.

2022-11-14 22:23 UTC, Dli3 commented on tests/modal.test.js
> +      if (page._parent._browserType._initializer.name === 'webkit') {
Thanks for the suggestion. I think that's a better approach. That way we don't need to deal with eslint not liking the underscores.

2022-11-15 01:21 UTC, Dli3 commented on tests/modal.test.js
> +        while (page.url().includes('#') && count < 10) {
Even though 4 tab count allowed the esc key to work for webkit majority of the time, I still found it testing at times when testing it. I found that when I used 10 it had a better success rate. 

Having this work around for webkit tests isn't the best approach. I submitted a ticket, [https://jira.corp.adobe.com/browse/MWPW-120941](url) , to add a focus trap. Hopefully this resolves the flaky modal tests on webkit.

2022-11-21 23:34 UTC, amauch-adobe approved these changes
Looks great!

2022-11-22 21:20 UTC, merged