CC regression - accordion feature
adobecom/nala pull request #334
Opened 2024-04-23 17:30 UTC by sigadamvenkata

CC regression - accordion feature
https://jira.corp.adobe.com/browse/MWPW-147151
https://jira.corp.adobe.com/browse/MWPW-147152
https://jira.corp.adobe.com/browse/MWPW-147153
https://jira.corp.adobe.com/browse/MWPW-147154

test case report from local:
![image](https://github.com/adobecom/nala/assets/130433161/ea8c14ab-c9b7-409e-b5ca-cb2c2c06368b)

2024-04-23 18:41 UTC, Dli3 commented
@sigadamvenkata Do you only run your tests on chrome?

2024-04-23 18:41 UTC, Dli3 commented
Does CC have their own unique accordion block? @sigadamvenkata

2024-04-23 19:23 UTC, amauch-adobe requested changes
Looks really good, like everyone else said handle the ESLint errors, I also added a small grammar fix and a recommendation to do instead of having a waitfor timeout call before checking the url link switch.

2024-04-23 19:23 UTC, amauch-adobe commented on tests/cc/accordion.test.js
> +  // erify accordion showing up with authored question and answers and UI
Missing 'V' in Verify within comment.

2024-04-23 19:23 UTC, amauch-adobe commented on tests/cc/accordion.test.js
> +      await page.waitForTimeout(1000);
As a recommendation I would look for a way to wait for an element on the subsequent page or it's load state to finish before checking the url since waiting for timeouts aren't very reliable since network or CI/CD pipeline issues could cause it to take longer than just a second.

2024-04-23 20:12 UTC, JackySun9 commented
@sigadamvenkata if you clone this from milo to cc, we might no need to do this, are you cloning the tests from milo?

2024-04-24 08:07 UTC, skumar09 approved these changes
Approving, 
Please fix the comments from @amauch-adobe

2024-04-29 08:10 UTC, sigadamvenkata commented
@amauch-adobe made the changes mentioned by you. 

@skumar09 @JackySun9 @Dli3

2024-04-29 16:44 UTC, amauch-adobe approved these changes
Approved. Thanks for addressing the fixes.

2024-04-29 16:49 UTC, merged