Adding link comparison script.
adobecom/nala pull request #343
Opened 2024-05-02 23:31 UTC by Dli3

[MWPW-146942](https://jira.corp.adobe.com/browse/MWPW-146942)
Adding link comparison script.

This script will go in and grab the links on page A and B. Then check that page B has the same hrefs associated to the link texts found in page A.

2024-05-03 15:22 UTC, JackySun9 requested changes

2024-05-03 15:22 UTC, JackySun9 commented on tests/bacom-blog/link-comparison.test.js
> +const data = JSON.parse(fs.readFileSync('./data/bacom-blog/stagedBlogUrls.json', 'utf8'));
you don't include the json file here

2024-05-03 15:22 UTC, JackySun9 commented on tests/bacom-blog/link-comparison.test.js
> +      await test.step('3. Verify that the links are the same in url A and B', async () => {
how do you make sure, urlA is comparing urlB, I mean if there is more links in urlB, the links will not match

2024-05-03 16:25 UTC, Dli3 commented on tests/bacom-blog/link-comparison.test.js
> +      await test.step('3. Verify that the links are the same in url A and B', async () => {
@JackySun9 We just want to make sure the links from A were not shuffled in B. There could've been authoring changes to B at the time of running the script, so we're not checking if they have the same length.

2024-05-03 16:26 UTC, Dli3 commented on tests/bacom-blog/link-comparison.test.js
> +const data = JSON.parse(fs.readFileSync('./data/bacom-blog/stagedBlogUrls.json', 'utf8'));
Do we want to include data files in our repo? @JackySun9 
cc @skumar09 @amauch-adobe

2024-05-03 16:36 UTC, JackySun9 commented on tests/bacom-blog/link-comparison.test.js
> +const data = JSON.parse(fs.readFileSync('./data/bacom-blog/stagedBlogUrls.json', 'utf8'));
are the urls dynamic?

2024-05-03 16:37 UTC, JackySun9 commented on tests/bacom-blog/link-comparison.test.js
> +      await test.step('3. Verify that the links are the same in url A and B', async () => {
could you give some examples?

2024-05-03 17:03 UTC, JasonHowellSlavin reviewed
Looks good, nothing needs to change, but some suggestions.

2024-05-03 17:03 UTC, JasonHowellSlavin commented on utils/linkComparison.js
> +  return diff;
Could use reduce, no need to change. 

```suggestion
export async function checkForDiff(a, b) {
  if (Object.keys(b).length === 0) return {};

  return Object.entries(a).reduce((rdx, [key, value]) => {
    const aValue = value ? value.toString() : value;
    const bValue = b[key] ? b[key].toString() : b[key];
    if (aValue !== bValue) {
      rdx[key] = [aValue, bValue];
    }
    return rdx;
  }, {});
```

2024-05-03 17:08 UTC, amauch-adobe approved these changes
Approved, made a small nit pick grammar change in a comment, but otherwise approved.

2024-05-03 17:08 UTC, amauch-adobe commented on tests/bacom-blog/link-comparison.test.js
> +      await test.step('3. Verify that the links are the same in url A and B', async () => {
@JackySun9 the reason for this test is to address a CSO issue where between bulk updating blog files the urls were no longer the same as they were before, meaning the links swapped around in the file that caused the links to no longer be valid.  It has led to discussions about the Franklin process of the word doc in sharepoint being converted to MarkDown for Franklin to use and then converted back to a Word doc with the updates in Sharepoint being there being the culprit for the scrambling of the links (according to Microsoft support).  This test is to help that situation.

2024-05-03 17:08 UTC, amauch-adobe commented on utils/linkComparison.js
> + * @description Finds the main tag and returns all the a tags found.
might want to change the 'a tags' to '<a> tags' in this comment so it is more clear.

2024-05-03 23:24 UTC, Dli3 commented on utils/linkComparison.js
> +  return diff;
Updated. Thanks @JasonHowellSlavin .

2024-05-03 23:25 UTC, Dli3 commented on tests/bacom-blog/link-comparison.test.js
> +const data = JSON.parse(fs.readFileSync('./data/bacom-blog/stagedBlogUrls.json', 'utf8'));
I didn't plan for it to be ran in CI/CD. @amauch-adobe 

@JackySun9 I've added the json file.

2024-05-03 23:26 UTC, Dli3 commented on tests/bacom-blog/link-comparison.test.js
> +      });
Thanks for the suggestion. I've updated it. @JasonHowellSlavin

2024-05-03 23:59 UTC, skumar09 approved these changes
@Dli3 : This looks good, as discussed will raise enhancement pr for link difference reporting, (like csv, or html)

2024-05-04 00:09 UTC, JackySun9 approved these changes

2024-05-04 00:20 UTC, merged