Pavantest
adobecom/nala pull request #345
Opened 2024-05-09 15:38 UTC by PavanKumarN8

@sigadamvenkata

2024-05-09 15:53 UTC, sigadamvenkata commented
@PavanKumarN8 can you attach locale run report aswell?

2024-05-09 15:55 UTC, PavanKumarN8 commented
![Screenshot (69)](https://github.com/adobecom/nala/assets/169047670/b7a7a015-6974-4c27-81a5-73b99cc63d8f)
All Test Cases are passed in local run

2024-05-10 16:01 UTC, JackySun9 approved these changes

2024-05-10 16:01 UTC, JackySun9 commented on configs/feds.config.js
> +        // baseURL: envs['@milo_live'],
add this here for adobe prod: {
      name: 'adobe-prod-chrome',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: envs['@adobe_prod'],
      },
    },

2024-05-10 16:02 UTC, JackySun9 requested changes
need to update locators

2024-05-15 04:53 UTC, PavanKumarN8 commented
Hi, @JackySun9 @sigadamvenkata I have pushed the modified code.

2024-05-16 05:21 UTC, JackySun9 commented on configs/feds.config.js
> +      name: 'adobe-prod-chrome',
I think we also need feds-live, just adobe-prod as new ones

2024-05-16 05:32 UTC, PavanKumarN8 commented on configs/feds.config.js
> +      name: 'adobe-prod-chrome',
Sure, I will change it.

2024-05-16 11:48 UTC, PavanKumarN8 commented
Hi @sigadamvenkata @JackySun9 I have added some of the test cases for HomePageSanity and updated the feds.config.js file as suggested.

2024-05-16 17:07 UTC, JackySun9 requested changes

2024-05-16 17:07 UTC, JackySun9 commented on configs/feds.config.js
> +    // baseURL: process.env.BASE_URL || envs['@milo_live'] || 'https://main--milo--adobecom.hlx.live',
No need to change this

2024-05-16 17:07 UTC, JackySun9 commented on features/feds/creativeCloudUnavSanity.spec.js
> +            unavElements: ['creativityAndDesign', 'adobeCreativeCloud', 'explore', 'features', 'forBusiness', 'comparePlans', 'learnAndSupport', 'buyNowButton', 'appSwitcher', 'signInButton']
If you have them in page object, why do you need them here

2024-05-16 17:07 UTC, JackySun9 commented on features/feds/locales/homePage.json
> +        "United States": {
if for different locales, they are the same, why do we need it

2024-05-16 17:07 UTC, JackySun9 commented on tests/feds/homePageSanity.test.js
> +        await validateLocalePage(page, baseURL, 13, "United States");
This is good, now the the code is super clear

2024-05-16 17:28 UTC, PavanKumarN8 commented on features/feds/creativeCloudUnavSanity.spec.js
> +            unavElements: ['creativityAndDesign', 'adobeCreativeCloud', 'explore', 'features', 'forBusiness', 'comparePlans', 'learnAndSupport', 'buyNowButton', 'appSwitcher', 'signInButton']
I have not modified the Creative Cloud test case, I will do so once the Home Page test cases are approved.

2024-05-16 17:32 UTC, PavanKumarN8 commented on features/feds/locales/homePage.json
> +        "United States": {
I am checking the visibility of the element for all locales under gnav, and it varies for each locale. Therefore, I have separated them according to locale in a JSON file to prevent script failures.

2024-05-17 04:28 UTC, PavanKumarN8 commented
Hi @sigadamvenkata @JackySun9 I have added Home Page Test Cases for all 91 locales

Local run report
![image](https://github.com/adobecom/nala/assets/169047670/5950a35b-fdab-4480-9860-1ceb675252ee)

2024-05-17 08:42 UTC, JackySun9 approved these changes

2024-05-19 15:06 UTC, sigadamvenkata approved these changes

2024-05-19 15:06 UTC, merged