MWPW-147289 [Nala] Refine screenshot diff tool
adobecom/nala pull request #346
Opened 2024-05-16 05:48 UTC by JackySun9

[MWPW-147289](https://jira.corp.adobe.com/browse/MWPW-147289)

1. Add IT s3 support, including upload, download and compare, clean base on aws s3 v3 SDK
will switch to public s3 later if need to run in github actions
3. redefine take APIs and move all from visualutil.js to take.js, with this, we can take full page or selector and take for one or two and compare them for diffs
4. update tests according to new take APIs

Examples to run them(you need key and secret for s3):
for UAR:
node run.js -c visual -p chrome,ipad,iphone -g uar-screenshots
node libs/screenshot/merge.js screenshots/uar
node libs/screenshot/uploads3.js screenshots/uar

for Milo:
node run.js -c visual -p chrome,ipad,iphone -g milo-screenshots
node libs/screenshot/merge.js screenshots/milo
node libs/screenshot/compare.mjs screenshots/milo
node libs/screenshot/uploads3.js screenshots/milo

for Feds:
node run.js -c visual -p chrome,ipad,iphone -g feds-screenshots
node libs/screenshot/merge.js screenshots/feds
node libs/screenshot/compare.mjs screenshots/feds
node libs/screenshot/uploads3.js screenshots/feds

for update milo base:
node libs/screenshot/cleans3.js milo screenshots/milo
node run.js -c visual -p chrome,ipad,iphone -g milo-screenshots
node libs/screenshot/merge.js screenshots/milo
node libs/screenshot/uploads3.js screenshots/milo

2024-05-22 22:39 UTC, Dli3 approved these changes

2024-05-23 23:16 UTC, amauch-adobe requested changes
This is awesome! I added a small comment on a class name, I also think it would be good to provide the test name under the screenshot comparison tiles on http://nala-auto.corp.adobe.com/, see my screenshot.

<img width="1206" alt="Screenshot 2024-05-23 at 5 13 52 PM" src="https://github.com/adobecom/nala/assets/56042473/c7a99db6-c125-4268-a1af-95feca6abf04">

2024-05-23 23:16 UTC, amauch-adobe commented on libs/screenshot/take.js
I feel like the name of this file should be changed to "capture" rather than "take".  I just feel like it is more clear than "take".  This is just my opinion though.

2024-05-23 23:31 UTC, JackySun9 commented on libs/screenshot/take.js
do you try the day mode on right top of the page, click the sun, but I will fix the dark mode

2024-05-23 23:33 UTC, JackySun9 commented on libs/screenshot/take.js
To be honest, I like take than capture, let us see other opinions

2024-05-24 02:18 UTC, JackySun9 commented on libs/screenshot/take.js
fixed @amauch-adobe

2024-05-24 17:56 UTC, JackySun9 commented
> @JackySun9, I can see that the projects/test names are there on the tiles, the color of the text just needs to be a lighter color so it can be seen. Other than that everything is good.

ok, got it

2024-06-04 17:44 UTC, JackySun9 commented
I will merge this first for fast validating PRs, if any concern, we can handle later

2024-06-04 17:44 UTC, merged