Home Page Test Scripts added for all locales
adobecom/nala pull request #348
Opened 2024-05-21 11:07 UTC by PavanKumarN8

Added Home Page Test Scripts for all locales 

CC: @sigadamvenkata

2024-05-21 16:42 UTC, Dli3 commented on tests/feds/homePageSanity.test.js
> +    test(`${features[25].name}, ${features[25].tags}`, async ({ page, baseURL }) => {
Add the country to your spec like:
` {
            tcid: '0',
            name: '@ArgentinaHomePageGnavCheck',
            path: '/ar/?georouting=off',
            tags: '@gnavsanity @gnavhomeargentina',
           country: 'France',
        },`

You can then do 
`  features.forEach((props) => {
 test(`${props.name}, $props.tags}`, async ({ page, baseURL }) => {
        await validateLocalePage(page, baseURL, props.tcid, props.country);
    });
}`
This would help you bring down your 400 lines in this test file.
cc @PavanKumarN8 @JackySun9 @sigadamvenkata @skumar09

2024-05-21 23:56 UTC, JackySun9 requested changes

2024-05-21 23:56 UTC, JackySun9 commented on features/feds/homePageSanity.spec.js
> +            name: '@ArgentinaHomePageGnavCheck',
can we have only one here, then use homePage.json to get the path?

2024-05-21 23:56 UTC, JackySun9 commented on features/feds/homePageSanity.spec.js
> +            name: '@ArgentinaHomePageGnavCheck',
I mean the path is not static like this, it is dynamic and load per homePage.json

2024-05-21 23:56 UTC, JackySun9 commented on tests/feds/homePageSanity.test.js
> +    const validateLocalePage = async (page, baseURL, featureIndex, locale) => {
agree to move into page object

2024-05-21 23:56 UTC, JackySun9 commented on features/feds/locales/homePage.json
> +            "unavElements": [
We have a lot of duplications here, can we have a common one, then just add difference ones if existing for other locales, make this clear and short

2024-05-21 23:56 UTC, JackySun9 commented on tests/feds/homePageSanity.test.js
> +    test(`${features[57].name}, ${features[57].tags}`, async ({ page, baseURL }) => {
If we use dynamic path, we can just need one test here

2024-05-22 02:24 UTC, PavanKumarN8 commented on tests/feds/homePageSanity.test.js
> +    const validateLocalePage = async (page, baseURL, featureIndex, locale) => {
Sure, I will move it into page object.

2024-05-22 02:29 UTC, PavanKumarN8 commented on tests/feds/homePageSanity.test.js
> +    test(`${features[13].name}, ${features[13].tags}`, async ({ page, baseURL }) => {
I have first tested tier 1 locales - JP, IT, US, UK, FR, & DE.

2024-05-22 02:30 UTC, PavanKumarN8 commented on tests/feds/homePageSanity.test.js
> +    test(`${features[25].name}, ${features[25].tags}`, async ({ page, baseURL }) => {
Sure, I will update it. Thanks, for the solution.

2024-05-22 03:07 UTC, PavanKumarN8 commented on features/feds/homePageSanity.spec.js
> +            name: '@ArgentinaHomePageGnavCheck',
Sure, I will try that.

2024-05-22 03:07 UTC, PavanKumarN8 commented on features/feds/locales/homePage.json
> +            "unavElements": [
Okay, sure.

2024-05-22 10:57 UTC, PavanKumarN8 commented on features/feds/homePageSanity.spec.js
> +            name: '@ArgentinaHomePageGnavCheck',
Hi @JackySun9, we are using this file to uniquely identify the locale, and all the values in the feature file are different from one another. However, I am unable to optimize it. If you have a solution, please help with this, and I am happy to modify it accordingly.

2024-05-22 11:03 UTC, PavanKumarN8 commented on features/feds/locales/homePage.json
> +            "unavElements": [
Hi @JackySun9, I agree that we have duplicate values, but the sequence and options will differ for each locale. Attempting to store common options and optimize them results in script failures. If you have a solution, please assist with this.

2024-05-22 14:58 UTC, JackySun9 commented on features/feds/homePageSanity.spec.js
> +            name: '@ArgentinaHomePageGnavCheck',
yes, I will try it later

2024-05-22 14:58 UTC, JackySun9 commented on features/feds/locales/homePage.json
> +            "unavElements": [
Yes, I will try this later

2024-05-22 18:11 UTC, JackySun9 commented
You just resolve other feedbacks, then can checkin, I will take a look later

2024-05-23 04:25 UTC, JackySun9 approved these changes

2024-05-23 23:27 UTC, JackySun9 commented
@Dli3 do you have any feedback on this?

2024-05-24 04:48 UTC, merged

2024-05-28 17:46 UTC, Dli3 commented
@PavanKumarN8 @sigadamvenkata This PR broke the eslint workflow. Please check the checks before merging.

Also, @PavanKumarN8 looks like you need to sign the Adobe CLA.