Creative Cloud Test Scripts added
adobecom/nala pull request #360
Opened 2024-06-03 05:35 UTC by PavanKumarN8

Hi @sigadamvenkata , Creative Cloud U-NAV Test Scripts added.

2024-06-03 05:46 UTC, PavanKumarN8 commented
![image](https://github.com/adobecom/nala/assets/169047670/e0cda37a-60eb-430a-9bde-26e45250de8a)

2024-06-05 18:17 UTC, JackySun9 commented on features/feds/prodSanity/creativeCloudUnavSanity.spec.js
> +    name: 'Creative Cloud UNAV Page',
please fix all eslint errors

2024-06-06 18:14 UTC, JackySun9 commented
one more eslint error, please fix

2024-06-06 21:08 UTC, skumar09 requested changes
Please fix eslint errors.

cc: @sigadamvenkata

2024-06-09 12:38 UTC, PavanKumarN8 commented
Hi, @JackySun9, @skumar09, eslint is not accepting json file type.
![image](https://github.com/adobecom/nala/assets/169047670/566b644e-ee18-4126-9f7d-d9e8474075c6)
Please assist with solving this error.
cc: @sigadamvenkata

2024-06-10 05:59 UTC, PavanKumarN8 commented
Hi, @JackySun9, @skumar09 all eslint errors fixed.

cc: @sigadamvenkata

2024-06-10 16:53 UTC, JackySun9 approved these changes

2024-06-11 04:44 UTC, sigadamvenkata approved these changes

2024-06-11 06:25 UTC, skumar09 approved these changes

2024-06-11 06:25 UTC, merged