Illustrator Test Scripts added
adobecom/nala pull request #372
Opened 2024-06-11 07:34 UTC by PavanKumarN8

Hi @sigadamvenkata, I have added Illustrator Test Scripts.

Local Test Run Results:
![image (1)](https://github.com/adobecom/nala/assets/169047670/e17b03a3-b5a2-4b5b-b164-e9a9660d6155)

2024-06-11 16:24 UTC, Dli3 requested changes
You need to sign the Adobe CLA.

2024-06-11 16:48 UTC, Dli3 commented on selectors/feds/feds.illustratorsanity.page.js
> +    await Promise.all(promises);
Do you need this?

2024-06-11 16:55 UTC, Dli3 commented on selectors/feds/feds.illustratorsanity.page.js
> +    await this.creativityAndDesign.click({ timeout: 5000 });
You use '.click({ timeout: 5000})' a lot in your PRs. If the default isn't meeting your needs, you can change the default in your team's config. See https://playwright.dev/docs/test-timeouts .

2024-06-11 17:06 UTC, Dli3 commented on selectors/feds/feds.illustratorsanity.page.js
> +    await test.step(`Validating ${locale} Locale Page`, async () => {
Why isn't this in your test file? You can probably break this down to multiple steps there.

2024-06-13 17:01 UTC, PavanKumarN8 commented
I will be raising the new PR with changes as discussed. Hence closing this.

2024-06-13 17:01 UTC, closed without merging