Optimized the code based on the review comments given for Illustrator
adobecom/nala pull request #382
Opened 2024-06-20 03:19 UTC by PavanKumarN8

Hi @sigadamvenkata, @JackySun9, @Dli3, and @skumar09, I have optimized the code based on the review comments provided for PR - https://github.com/adobecom/nala/pull/381

Locale Test Run Results
![Screenshot (103)](https://github.com/adobecom/nala/assets/169047670/6fbf4ec8-e9e3-46d8-92e3-3361f5161f15)

2024-06-20 15:15 UTC, JackySun9 requested changes

2024-06-20 15:15 UTC, JackySun9 commented on selectors/feds/feds.illustratorsanity.page.js
> +    await Promise.all(elements.map(async (element) => {
rewrite like this:

await Promise.all(elements.map(async (element) => {
  switch (element) {
    case this.tryItForFree:
      if (country === 'Germany') {
        await expect(element).toBeVisible();
      }
      break;
    
    case this.appSwitcher:
    case this.signInButton:
      const excludedCountries = [
        'United Kingdom', 'India', 'Canada English', 'Canada French',
        'Mexico', 'Australia', 'Indonesia', 'Indonesia English',
        'Thailand', 'Thailand English', 'Singapore', 'Philippines',
        'Philippines English', 'Middle East And North Africa'
      ];

      if (!excludedCountries.includes(country)) {
        await expect(element).toBeVisible();
      }
      break;
    
    case this.signInButtonTwo:
      const includedCountries = [
        'United Kingdom', 'India', 'Canada English', 'Canada French',
        'Mexico', 'Australia', 'Indonesia', 'Indonesia English',
        'Thailand', 'Thailand English', 'Singapore', 'Philippines',
        'Philippines English', 'Middle East And North Africa'
      ];

      if (includedCountries.includes(country)) {
        await expect(element).toBeVisible();
      }
      break;

    default:
      await expect(element).toBeVisible();
  }
}));

2024-06-20 15:15 UTC, JackySun9 commented on selectors/feds/feds.illustratorsanity.page.js
> +        case this.signInButton:
reuse above array

2024-06-21 05:37 UTC, PavanKumarN8 commented on selectors/feds/feds.illustratorsanity.page.js
> +    await Promise.all(elements.map(async (element) => {
Hi @JackySun9, I have updated the code as per the suggestions.

Thanks.

2024-06-21 17:02 UTC, JackySun9 approved these changes

2024-06-25 04:35 UTC, skumar09 approved these changes

2024-06-25 05:27 UTC, merged