news-block test cases
adobecom/nala pull request #387
Opened 2024-07-03 08:05 UTC by cod17828

PR includes

implementation of non-logged in and logged in scenarios of news-block
config changes (run dx nala tests on feature branch from which pr is created, or on partners.stage.adobe.com)

2024-07-08 16:49 UTC, Dli3 commented on tests/dx/news.test.js
> +    await newsPage.IMSEmailPage.waitFor({ state: 'visible', timeout: 5000 });
You probably don't need this wait. Your emailField.fill() should autowait already. Please see https://playwright.dev/docs/actionability.

2024-07-08 17:40 UTC, Dli3 commented on tests/dx/news.test.js
> +  async function runLoginTest({
You don't want to add these functions to your page object class?

2024-07-08 18:23 UTC, Dli3 commented on tests/dx/news.test.js
> +      await newsPage.firstCardDate.waitFor({ state: 'visible', timeout: 10000 });
You probably don't need this wait. Your emailField.fill() should autowait already. Please see https://playwright.dev/docs/actionability.

2024-07-12 15:57 UTC, Dli3 commented on tests/dx/news.test.js
> +    {
I think you can add this to your spec file. Maybe add a data key. 
For example:
  ```
  {
      tcid: '8',
      name: '@login-news-page-silver-user',
      path: '/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-news @regression @login',
      data: {
      partnerLevel: 'spp-bronze:',
      resultTotal: 11,
      cardPartnerLevel: 'Automation regression news card SPP Bronze no1',
      cardPartnerLevelAbove: 'Automation regression news card spp silver no1',
}
    },
```

2024-07-12 16:00 UTC, Dli3 approved these changes

2024-07-12 18:11 UTC, skumar09 requested changes

2024-07-12 18:11 UTC, skumar09 commented on tests/dx/news.test.js
> +    {
Yes, pls include the test case, and test data in `.spec `file

2024-07-15 12:51 UTC, cod17828 commented on tests/dx/news.test.js
> +    await newsPage.IMSEmailPage.waitFor({ state: 'visible', timeout: 5000 });
@skumar09 why would it not pick GitHub .env variables?

2024-07-15 20:28 UTC, JackySun9 approved these changes

2024-07-17 15:43 UTC, skumar09 approved these changes

2024-07-18 07:53 UTC, merged