Added options to run tests against localhost.
adobecom/nala pull request #42
Opened 2022-12-13 00:44 UTC by Dli3

Adding options to run Nala tests against localhost 3000 and 6456. 
Ticket: https://jira.corp.adobe.com/browse/MWPW-119683  

In order to test against localhost, the user would have to run the runLocalRegression.sh script. If they don't specify a tag with the -t flag, it'll run all tests. If the 6456 port isn't specified with the -p flag, it'll default to port 3000. 

What the script does: 
1. Updates the envs line in ".feature" files to add either "@localhost:3000" or "@localhost:6456" and comments the existing value out. 
2. It then runs the tests against localhost.
3. It then reverts the envs back to their previous value.

2022-12-13 17:23 UTC, Brandon32 approved these changes

2022-12-13 18:15 UTC, amauch-adobe requested changes
This looks really good!

- One change I would add is the ability to choose a browser to run on.  Meaning, allow the option to choose to run tests locally only on one browser they choose (Chromium, Firefox, or Safari) and then too also keep the option to run on all browsers.  So by default it would run on all browsers headless, but if a specific browser flag is sent in (I would make it similar to how playwright currently allows it, i.e., look [here](https://playwright.dev/docs/test-cli).  
- I think it would also be good to give them the option to run it headless or headed, headless by default
- Also, quick question, was there a reason for choosing to make a separate shell file instead of creating a different conditional or flag within the original run.sh file.  Just thinking that might remove the need to have a separate shell file and instead just have a conditional flag for choosing which flow to execute.

2022-12-17 00:05 UTC, Dli3 commented
> This looks really good!
> 
> * One change I would add is the ability to choose a browser to run on.  Meaning, allow the option to choose to run tests locally only on one browser they choose (Chromium, Firefox, or Safari) and then too also keep the option to run on all browsers.  So by default it would run on all browsers headless, but if a specific browser flag is sent in (I would make it similar to how playwright currently allows it, i.e., look [here](https://playwright.dev/docs/test-cli).
> * I think it would also be good to give them the option to run it headless or headed, headless by default
> * Also, quick question, was there a reason for choosing to make a separate shell file instead of creating a different conditional or flag within the original run.sh file.  Just thinking that might remove the need to have a separate shell file and instead just have a conditional flag for choosing which flow to execute.

Thanks! I've made the update with the added options.

I created a separate file for clarify and because there are a lot more arguments to handle in the local run script. I thought adding it to the run.sh would get pretty messy having it in nested conditional statements.

2023-01-10 02:32 UTC, amauch-adobe approved these changes
All changes look good, thanks.

2023-01-11 00:06 UTC, merged