Custom reporters
adobecom/nala pull request #56
Opened 2023-01-19 18:36 UTC by JingleH

we can start using these custom reporters and generating data

i've tested the changes in my own fork of Nala [https://github.com/JingleH/nala/actions/runs/3961304265](https://github.com/JingleH/nala/actions/runs/3961304265)

API endpoints for the api-reporter are implemented in [https://git.corp.adobe.com/jinglhua/nala-api-testruns](https://git.corp.adobe.com/jinglhua/nala-api-testruns). Documentations are still in progress, and I'm thinking if and when we need to "publish" it, e.g. setting up Service Registry, CMR workflows, monitoring and CSOs, a better domain name, and jumping through hoops to get security review

Dashboard frontend that uses these APIs are also still in progress

2023-01-19 22:48 UTC, amauch-adobe requested changes
See my comments in line.

2023-01-19 22:48 UTC, amauch-adobe commented on utils/verify-specs.js
> +const fs = require('fs/promises');
See my comments on the package.json file.  I really don't know if we need this file since a test shouldn't be added, and neither can run without having a .spec file in the features directory.  No tests should even be added/merged into the main branch without it. Plus in the future, every team will have its own repositories which would then have their .spec files located there and not in Nala's repo.  I guess I'm just trying to understand the need for this validation checker.

2023-01-19 22:48 UTC, amauch-adobe commented on utils/verify-specs.js
> +const fs = require('fs/promises');
Is this for the UI, to ensure the titles for the reporting are correct and have what is needed?  If so, how are these going to be connected, and what is the process for the usage of this validator?

2023-01-19 22:48 UTC, amauch-adobe commented on reporters/api-reporter.js
> +// FIXME: use GitHub Actions Environment variables
Probably want to remove this comment unless there is still work that needs to be done in a subsequent PR to address it.

2023-01-19 22:48 UTC, amauch-adobe commented on reporters/api-reporter.js
> +// FIXME: use GitHub Actions Environment variables
I also think maybe it would be best for the reporter's directory/files should be moved to utils rather the be top-level.  Just an opinion, not an actual requirement or anything.

2023-01-19 23:16 UTC, JingleH commented on utils/verify-specs.js
> +const fs = require('fs/promises');
my original intent was to catch errors fail early and not during test runs. But this is definitely not necessary, so I'll remove it

2023-01-19 23:22 UTC, JingleH commented on .github/workflows/manual.yml
> +
done!

2023-01-19 23:25 UTC, JingleH commented on reporters/api-reporter.js
> +// FIXME: use GitHub Actions Environment variables
Originally I thought it's generally a better practice to keep configuration separate from code. Now on a second thought, since Milo will be pulling and pulling the code directly (at least it is for now), keeping non-credential and non-frequently-changing configurations in code allows consumers like Milo to not have to update its GitHub Actions Env Vars and can just run it. So let's keep it in code!

2023-01-19 23:26 UTC, JingleH commented on package.json
> +    "verify:specs": "node ./utils/verify-specs.js"
my original intent was to catch errors fail early and not during test runs. But this is definitely not necessary, so I'll remove it

2023-01-21 00:30 UTC, amauch-adobe approved these changes
This is awesome, great work.  I approve of the changes.

2023-01-27 19:31 UTC, merged