build automation for existing quiz page in nala
adobecom/nala pull request #59
Opened 2023-02-06 19:49 UTC by JackySun9

https://jira.corp.adobe.com/browse/MWPW-125387

1. build automation test for existing quiz page, https://www.adobe.com/creativecloud/quiz-recommender.html?mboxDisable=1
2. try data provider with static data
3. use js-yaml to load test data
4. enable json reporter for local test

2023-02-06 20:50 UTC, amauch-adobe requested changes
Jacky Sun, this is awesome!  Way to go migrating over a test to Nala.  I left various comments and requested changes.  I think it would be best to move out your data files to a top-level data directory with a subdirectory named after your Milo-based site.  For example, nala/data/dc/. The Frictionless team handles the document cloud milo-based site, so there site is named dc.  I would do that instead of having so many directories under the tests/ directory.  Also, if you really need a common file as well, I would do the same by adding a top-level nala/common/<site-name>/ directory.

2023-02-06 20:50 UTC, amauch-adobe commented on selectors/quiz.selectors.js
> +  '@answer': '//div[@class="quiz-options"]//*[@aria-label="answer"]',
XPaths are available as locators for Playwright albeit it isn't the best option for finding an element.  See the documentation [here](https://playwright.dev/docs/best-practices#prefer-user-facing-attributes-to-xpath-or-css-selectors) for why it isn't the best practice.  If you can find an element using a better locator option, it's best you do.

2023-02-06 20:50 UTC, amauch-adobe commented on package.json
> +    "js-yaml": "^4.1.0"
Not a problem, just keep in mind in the future specific dependencies that will be needed for a particular test will be held under your own site's repo rather than in Nala (unless it becomes a core dependency based on Infra meetings).

2023-02-06 20:50 UTC, amauch-adobe commented on features/quiz.spec.js
> +        '/creativecloud/quiz-recommender.html?mboxDisable=1',
This concept of adding a parameter to the path variable works fine if you just plan on having this test only ever execute against the 'main' branch. If you decide to run this test in GitHub actions against a specific PR that has a specific feature branch this will **break**.  Nala automatically will add during the parse method "?milolibs=<featureBranchName>" to the end of your URL to test the feature branch against the specific environment desired, in this case www.adobe.com.  I would probably instead add your parameter after the fact that the parse(spec.js file) has been done.  For example, ` await clickEachAnswer(`${props.url}?mboxDisable=1`, page, key);`.  You will need to add a condition to check if the URL already contains "?milolibs=" in it to decide whether to append it with an "&" or not but that will relieve the problem of it braking if used against a feature branch PR.

2023-02-06 20:50 UTC, amauch-adobe commented on tests/quiz/quiz.common.js
> +  // console.log(answers);
nitpick, probably should remove the commented-out code line.

2023-02-06 20:50 UTC, amauch-adobe commented on tests/quiz/quiz.common.js
> +  // console.log(acturalProduct);
nitpick, probably should remove the commented-out code line.

2023-02-06 20:50 UTC, amauch-adobe commented on tests/quiz/quiz.common.js
> +/* eslint-disable no-restricted-syntax */
word of caution, which I'm sure you have a reason for it, the point of ESLint is to help standardize code and keep it in compliance.  If we always disable it, especially for the entire file, what is the point of having it?  Milo/Nala has a strict push for compliance, it is always best to find a way to make code calls, logic, etc. that are compliant.

2023-02-06 20:50 UTC, amauch-adobe commented on tests/quiz/quiz.common.js
> +async function clickEachAnswer(url, page, data) {
Question, are you planning on using the clickEachAnswer() and checkResultsPage() methods outside of the quiz test?  If so, and you have an actual case coming up, then let's create the common directory, but if not and you are just considering it in the future that may or may not happen, let's **not.** Milo/Nala follows the structure of not adding things in areas where it isn't necessary until it becomes necessary.  So, if you don't have a use case for needing these methods in a common directory, meaning there is another test that will use the exact same methods outside of the quiz method, it should be just housed in the quiz.test.js file.

2023-02-06 20:50 UTC, amauch-adobe commented on tests/quiz/quiz.common.js
> +      await page.getByRole('button', { name: selectors['@next-button'] }).click();
Nice usage of strict locators!

2023-02-06 20:50 UTC, amauch-adobe commented on tests/quiz/quiz.test.js
> +/* eslint-disable no-restricted-syntax */
Same comment as the quiz.common.js file, let's try to find ways to be compliant rather than create exceptions.

2023-02-06 20:50 UTC, amauch-adobe commented on playwright.config.js
> +    : [['list'], ['./utils/reporters/json-reporter.js']],
What is the exact need for adding the json-reporter to the normal playwright executions, meaning outside of the CI/CD pipeline in GitHub?  The json-reporter is strictly necessary for the Nala Dashboard application.  I might have missed it in your code, but I didn't see it anywhere you needed this report.  Do you have a need for it?

2023-02-07 04:57 UTC, JackySun9 commented on package.json
> +    "js-yaml": "^4.1.0"
ok

2023-02-07 04:57 UTC, JackySun9 commented on features/quiz.spec.js
> +        '/creativecloud/quiz-recommender.html?mboxDisable=1',
ok, got it

2023-02-07 04:57 UTC, JackySun9 commented on playwright.config.js
> +    : [['list'], ['./utils/reporters/json-reporter.js']],
ok, remove it

2023-02-07 05:01 UTC, JackySun9 commented on selectors/quiz.selectors.js
> +  '@answer': '//div[@class="quiz-options"]//*[@aria-label="answer"]',
I tried other ways, this is only way I found to make it work for all text

2023-02-07 05:01 UTC, JackySun9 commented on tests/quiz/quiz.common.js
> +/* eslint-disable no-restricted-syntax */
Fixed it

2023-02-07 05:01 UTC, JackySun9 commented on tests/quiz/quiz.common.js
> +async function clickEachAnswer(url, page, data) {
Fixed it

2023-02-07 05:02 UTC, JackySun9 commented on tests/quiz/quiz.common.js
> +      await page.getByRole('button', { name: selectors['@next-button'] }).click();
I tried other ways, not working

2023-02-07 05:02 UTC, JackySun9 commented on tests/quiz/quiz.common.js
> +  // console.log(acturalProduct);
Fixed it

2023-02-07 17:05 UTC, amauch-adobe commented on tests/quiz/quiz.common.js
> +      await page.getByRole('button', { name: selectors['@next-button'] }).click();
oh, you are fine.  I actually was complementing how you chose to use the more strict locator over just a CSS selector.  So good job!

2023-02-07 17:15 UTC, amauch-adobe approved these changes
Thanks for addressing the changes @JackySun9, this looks great!  The code is approved, but before we can merge it into Nala we need to see that the tests pass in GitHub Actions.  Something you can do is use the 'Run Nala Debugging' GitHub Action Workflow, you will find it under the actions tab in GitHub under your forked repository URL page.  This workflow just needs you to tell it what branch to run Nala on, the default is 'main', and then supply it a test tag from your quiz.spec.js file, my guess is you will want to use '@quiz'.  Let it run and then you can download the playwright report artifact and upload the trace files for each test iteration at the Playwrights Trace Viewer [here](https://trace.playwright.dev/)

2023-02-07 17:36 UTC, skumar09 reviewed
@JackySun9 , 
- would like to understand bit more on the test data files (.yml), and see if there is any other way to feed the data? 
- can we sync up sometime when you are free?..

2023-02-08 00:49 UTC, Dli3 approved these changes

2023-02-14 03:51 UTC, amauch-adobe commented
After having some slack conversations with Jacky Sun, it turns out this is a POC for right now while his team is creating the actual Milo/Franklin-based pages.  Currently, the test executes against AEM pages, we do not want to use Nala to test AEM pages.  The Nala Automation framework is meant to test Milo blocks and Milo-based consumer sites.  For this reason, I felt it is best to hold off merging this into Nala until the test/PR is adjusted to use real Milo/Franklin pages and not AEM pages especially since it might change test timeouts, parallel executions, etc. due to the performance of Milo vs. AEM.

cc @Dli3, @skumar09

2023-05-03 21:36 UTC, amauch-adobe requested changes
Just a few comments, but well done, I like the test a lot!

2023-05-03 21:36 UTC, amauch-adobe commented on features/uar/quiz.spec.js
> +      tcid: '1',
I think tcid's start at 0?  @skumar09 can clarify if it is required or not though.

2023-05-03 21:36 UTC, amauch-adobe commented on features/uar/result.spec.js
> +      tcid: '1',
I think tcid's start at 0?  @skumar09 can clarify if it is required or not though.

2023-05-03 21:36 UTC, amauch-adobe commented on libs/data-provider.js
> +/**
It would be good to add a method description so when used in an IDE it will pick it up for auto-complete.

2023-05-03 21:36 UTC, amauch-adobe commented on libs/data-provider.js
> + * @param {string} path
It would be good to add a method description so when used in an IDE it will pick it up for auto-complete.

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/quiz.page.js
> +   * @param {string} url
Missing method description

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/quiz.page.js
Just a reminder on CSS selectors and XPath locators, performance wise they take the longest.  If you can use ids or class names, etc. that is preferred.

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/quiz.page.js
> +   * @param {string} result
Missing method description.

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/result.page.js
Same case, just a reminder on CSS/XPath selectors in Playwright they are not as performant as they provided locators.  https://playwright.dev/docs/locators

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/result.page.js
POM methods should have method descriptions for auto-complete usage in IDEs.

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/result.page.js
> +    await this.page.reload();
Do you need to refresh the page right after going to the page?  Just curious, not a concern, just wondering.  Maybe add a note if it is needed.

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/result.page.js
> +      await this.page.waitForTimeout(1000);
Just a recommendation (not a requirement), when I add basically a timeout like this (similar to a thread sleep or an implicit/explicit wait) it helps to explain why since Playwright recommends not to use them unless absolutely needed.

2023-05-03 21:36 UTC, amauch-adobe commented on selectors/uar/result.page.js
> +      await this.page.reload();
Same case as the previous reload call it would be best to explain the need for calling it.

2023-05-03 21:36 UTC, amauch-adobe commented on tests/uar/result.test.js
> +  // test.setTimeout(10 * 60 * 1000);
small nitpick if the test timeout is no longer necessary, we could remove the code and comment.

2023-05-03 21:36 UTC, amauch-adobe commented on tests/uar/result.test.js
> +          page.waitForTimeout(5000);
Good to explain why we need a 5sec timeout here.

2023-05-03 21:36 UTC, amauch-adobe commented on tests/uar/quiz.test.js
> +  test.setTimeout(3 * 60 * 1000);
Good to explain the need for a 3min test timeout for clarification, especially for future purposes of test performance audit in the CI execution.  Just an idea.

2023-05-03 21:39 UTC, amauch-adobe commented
@JackySun9 it looks like your test uses the baseUrl construct which requires having a config.js in the /configs directory.  Are you using the acom.config.js file to pull your baseUrl?  If so we will need to use the specific label on your PR so the Nala CI knows which config to use for your test execution.

2023-05-04 15:44 UTC, JackySun9 commented
> 

yes, thanks!

2023-05-04 17:01 UTC, JackySun9 commented on selectors/uar/result.page.js
Got it, thanks!

2023-05-04 17:04 UTC, JackySun9 commented
@amauch-adobe thanks for your feedback, I resolved all your concerns

2023-05-04 17:43 UTC, Dli3 commented on features/uar/quiz.spec.js
> +      tcid: '1',
Might be good to clarify this because he started at 1 in [the carousel test](https://github.com/adobecom/nala/blob/main/features/milo/carousel.block.spec.js). 
@amauch-adobe @skumar09 @JackySun9

2023-05-04 18:03 UTC, skumar09 commented
@JackySun9  Welcome to Nala, !! Nice to see UAR PR 
provided few review inputs, pls review and update.

2023-05-04 18:03 UTC, skumar09 requested changes

2023-05-04 18:42 UTC, JackySun9 commented
@skumar09 I updated them according to your feedback, thanks!

2023-05-04 18:54 UTC, amauch-adobe approved these changes
Looks great!

2023-05-04 20:39 UTC, Dli3 approved these changes

2023-05-04 21:30 UTC, merged