Fix URL for DC PR testing
adobecom/nala pull request #61
Opened 2023-02-09 23:32 UTC by JFernandezAdobe

Running Nala tests against PRs in DC repo is failing:
https://github.com/adobecom/dc/actions/runs/4137313683/jobs/7152322306

The test URL is wrong:
https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt?milolibs=MWPW-125749-review-desing-details

It should be:
https://MWPW-125749-review-desing-details--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt 

Related ticket: [MWPW-125473](https://jira.corp.adobe.com/browse/MWPW-125473)

2023-02-14 03:47 UTC, amauch-adobe requested changes
As I mentioned in our slack:

I have a different idea that I think will be more maintainable as more sites come on board with using Nala.  I've added my comments and what I think should be changed for your PR.

2023-02-14 03:47 UTC, amauch-adobe commented on features/parse.js
> +  if (!env.match(/@milo|@dc/) && !url.includes('--dc')) {
to make this more maintainable for the future of different sites coming on board we should do this:

```
function buildUrl(url, env) {
  let { branch } = process.env;
  let { repoName } = process.env;
  if (!branch) return url;
  if (branch.includes('/')) {
    const branchPath = branch.split('/');
    if (branchPath.length > 1) {
      let branchBuild = '';
      branchPath.forEach((pathName) => {
        branchBuild += `${pathName}-`;
      });
      branch = branchBuild.slice(0, (branchBuild.lastIndexOf('-')));
    }
  }
  if (!repoName) {
    repoName = 'milo';
  } else {
    repoName = repoName.substring(repoName.lastIndexOf('/'));
  }
  if (env !== `@${repoName}` && !url.match(/hlx.live|hlx.page/)) {
    return `${url}?milolibs=${branch}`;
  }
  return url.replace('main', branch);
}
```
The repoName variable will be pulled into the github actions workflow file on everyone's separate site repo.  We would call the `github.repository` value in the YAML file and set it to repoName.  Repository names are like 'adobecom/dc or adobecom/milo, respectively.  This way we won't have to keep adding more if statements with every site's naming.

2023-02-14 03:47 UTC, amauch-adobe commented on features/parse.js
> +  if (!branch) return env.match(/@dc_stage|@dc_prod/) ? `${url}.html` : url;
So I would do this in your dc_converter.spec file:

```
module.exports = {
  name: 'DC Converter',
  features: [
    {
      name: '@converter',
      path: [
        '/acrobat/online/pdf-to-ppt',
      ],
      envs: '@dc_preview',
      tags: '@pdf-converter',
    },
    {
      name: '@converter',
      path: [
        '/acrobat/online/pdf-to-ppt.html',
      ],
      envs: '@dc_prod',
      tags: '@pdf-converter',
    },
  ],
};

```

2023-02-14 03:47 UTC, amauch-adobe commented on features/parse.js
> +  if (!branch) return env.match(/@dc_stage|@dc_prod/) ? `${url}.html` : url;
It's best to keep specific site implementation requirements within spec files or in the future months of your site's repo instead of adding it to the core nala utilities.

2023-02-14 20:02 UTC, amauch-adobe approved these changes
Approved.

2023-02-16 22:11 UTC, JackySun9 approved these changes

2023-02-17 00:53 UTC, merged