Test all L2 converter verbs
adobecom/nala pull request #63
Opened 2023-02-10 23:03 UTC by JFernandezAdobe

Jira ticket: [MWPW-126088](https://jira.corp.adobe.com/browse/MWPW-126088)

Test will cover the following E2E conversion flow:

1. Upload a test document
2. Wait for conversion to complete
3. Wait for file preview
4. Download the converted file

Test pages:
https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-jpg
https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-word
https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-excel
https://main--dc--adobecom.hlx.page/acrobat/online/convert-pdf
https://main--dc--adobecom.hlx.page/acrobat/online/ppt-to-pdf
https://main--dc--adobecom.hlx.page/acrobat/online/jpg-to-pdf
https://main--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
https://main--dc--adobecom.hlx.page/acrobat/online/excel-to-pdf

2023-02-13 22:22 UTC, JFernandezAdobe commented
Hi @amauch-adobe, FYI this PR requires that the previous PR be merged first for the tests to pass.
Thanks!
https://github.com/adobecom/nala/pull/61

2023-02-14 05:56 UTC, amauch-adobe requested changes
Looks good, my only request is to move your data docs down a directory, meaning move them to /docs/dc.  That way we can separate other teams' docs and organize things for the time being, and then in the future make it easier to pull out teams' code/files to their separate repos.

2023-02-14 05:56 UTC, amauch-adobe commented on features/dc_converter.spec.js
>        envs: '@dc_preview @dc_prod',
See my previous comments in PR #61 about how you can separate URLs that require the .HTML extension in your spec file.  The Parse.js file shouldn't have specific implementation outside of the normal core Franklin/Milo support.  Having the .HTML extension isn't Milo/Franklin's best practice but required support for legacy compatibility.  It should remain either in Specs or test implementations and not core Nala.

2023-02-14 19:37 UTC, Dli3 approved these changes

2023-02-14 19:59 UTC, amauch-adobe approved these changes
Approved.

2023-02-17 01:15 UTC, merged