[MWPW-126307] Added first FEDS consent check
adobecom/nala pull request #69
Opened 2023-02-21 14:19 UTC by chadsunvice

Current status: Eurovision is working on adding new FEDS features into our feature-branch. 
Current checks being added run on feds-gnav branch.

2023-02-21 16:39 UTC, amauch-adobe commented on .gitignore
> +Test.pptx
I'm going to reach out to Frictionless to have an actual directory created to test downloads so we can ignore the directory rather than keep adding each file to the ignore list.  For now, though this will work.

2023-02-21 16:55 UTC, amauch-adobe requested changes
@chadsunvice this is an excellent test, good job on your first test using Nala/Playwright.  I just had a few comments and one specific requested change that needs to be made before this can be merged.  Once again, great job!

2023-02-21 16:55 UTC, amauch-adobe commented on envs/envs.js
> +  '@milo': 'https://main--milo--adobecom.hlx.live',
Please don't change the naming constructs of the envs.js for the tag names.  All names either have to have _preview for hlx.page, _live for hlx.live, or _stage for stage.<domain_name>, and _prod for production domain urls.  Our parse.js requires that construct to correctly create urls for testing on PRs as well as the Nala Dashboard Test Results application coming soon.  You might just needed to update your fork to the latest main.

2023-02-21 16:55 UTC, amauch-adobe commented on envs/envs.js
> +  '@milo': 'https://main--milo--adobecom.hlx.live',
Also, as a word of caution the hlx.page URLs are not behind any caching so they will be more taxing against the Franklin services.  For test development, authoring, and engineering development hlx.page URLs are perfect for those types of actions.  As soon as the page under test is published it is best to use hlx.live URLs instead or the actual production URLs.  hlx.live URLs are behind caching but may not have all of the other services running against them, for example, chat.  If you are testing a page that is located under a /drafts/ directory in your site's folder in Sharepoint, the risk level of harm for having that page published under drafts is so small since we filter out those pages being indexed or let alone connected to any level of path caching in Akamai or CDNs that the likelihood of someone going to that page other than internal employees is very small.  That is why Milo's block testing is done under the drafts directory and has pages already published so that we can use hlx.live URLs and tax the Franklin services less due to caching.

2023-02-21 16:55 UTC, amauch-adobe commented on features/consent.spec.js
> +      envs: '@feds',
will need to change envs to '@feds_live'

2023-02-21 18:43 UTC, JackySun9 requested changes

2023-02-21 18:43 UTC, JackySun9 commented on tests/consent.test.js
> +      await page.waitForSelector(selectors['@OneTrustContainer']);
For consent banner, it will only show for some locales, do you need mock GEO for it?

2023-02-22 11:39 UTC, narcis-radu commented on tests/consent.test.js
> +      await page.waitForSelector(selectors['@OneTrustContainer']);
Good point @JackySun9 ! We developed some helpers to allow mocking geo location, @chadsunvice can introduce them and make sure the consent banner is displayed.

2023-02-22 11:49 UTC, narcis-radu commented on selectors/consent.selectors.js
> +  '@OneTrustModalClose': 'button.save-and-close'
Looks like this selector `button.save-and-close` is duplicated. We should update the value to `#close-pc-btn-handler`. Generally speaking, it would be a good idea to have specific selector and make sure we don't select unwanted elements (e.g. button.save-and-close might be the button from a random form).

2023-02-22 11:49 UTC, narcis-radu commented on tests/consent.test.js
> +      const url = props.title.match(/stage|prod/) ? `${props.url}.html` : props.url;
I don't think we have use-cases for pages with `.html` extension 🤔

2023-02-22 11:49 UTC, narcis-radu commented on tests/consent.test.js
> +      await page.waitForSelector(selectors['@OneTrustContainer']);
`?customPrivacyLocation=de` should force the banner to show up.

2023-02-22 11:49 UTC, narcis-radu commented on tests/consent.test.js
> +      await expect(OneTrustTitle).toHaveText('Make It Your Own');
Title will be different based on locale, maybe we shout expect for a DOM element with class <x> that holds the title text; the same for other expectations.

2023-02-22 13:44 UTC, chadsunvice commented on .gitignore
> +Test.pptx
I agree @amauch-adobe. I'll keep as-is and we can remove those in the future.

2023-02-23 13:43 UTC, narcis-radu commented on envs/envs.js
> +  '@milo_prod': 'https://milo.adobe.com/',
The extra `/` added might break things

2023-02-23 13:43 UTC, narcis-radu commented on tests/consent.test.js
> +      // !Note: OneTrust only loads on a specific subset of locales.
The banner gets loaded only on GDPR enforced countries.

2023-02-23 14:16 UTC, narcis-radu commented on envs/envs.js
> +  '@milo_prod': 'https://milo.adobe.com/',
@chadsunvice - not sure I understand the 👎 so I will try to add more context: in your PR you added an extra `/` to `@milo_prod` and I'm concerned it will break things, the end URL will be something like `milo.adobe.com//path/to/page`. I checked the file in `main` branch and it does not have the extra `/`. I don't think this is an update you inherited from merging.
Here's the file in the main branch - https://github.com/adobecom/nala/blob/main/envs/envs.js#L3

2023-02-23 18:45 UTC, JackySun9 commented on features/parse.js
> +    repoName = 'milo_live';
milo repo name is milo, right?

2023-02-23 19:24 UTC, amauch-adobe commented on envs/envs.js
> +  '@milo_prod': 'https://milo.adobe.com/',
yeah, none of the environment domains in envs.js should have a trailing forward slash at the end since the path variable in the feature.spec file has the forward slash added to the URLs there.

2023-02-23 19:27 UTC, amauch-adobe commented on features/parse.js
> +    repoName = 'milo_live';
yeah, there shouldn't be any change to the parse.js file being made in test PRs.  Where that is a core Nala script file any changes should be made separately outside of additional test PRs.  And @JackySun9 you are correct it should just be 'milo' and NOT 'milo_live'.

2023-02-23 19:34 UTC, amauch-adobe requested changes
Just a requested revert to the features/parse.js.

2023-02-23 19:34 UTC, amauch-adobe commented on features/parse.js
> +    repoName = 'milo_live';
So this shouldn't be changed.  Lets revert the commit for this line so it stays as repoName = 'milo'.  The actual repository name comes from github's API during the github actions workflow, it sends the entire short name of the repository that executes the github action, i.e., adobecom/milo or if for 'DC' it would grab adobecom/dc.  We use this naming to decide how the feature branch that is being tested should be added to the url, either ?milolibs=featurebranch or replacing the "main" in the hlx.live url to the feature branch name.

2023-02-24 08:42 UTC, narcis-radu approved these changes

2023-02-24 20:24 UTC, merged