MWPW-127667 Update playwright configuration
adobecom/nala pull request #76
Opened 2023-03-08 07:22 UTC by skumar09

MWPW-127667 : Update Nala playwright configuration for following requirements

- Parallel run 
    -  Parallel run is enabled but number of workers count parameter was not updated.
    -  Updated workers count = 2  
- Provide path for test-results folder
   - Added the test result path
- Provided path for local -test debug html results
   - Added path for html test results for local env debugging 
   - This doesn't have impact on github action or CI execution
- Updated actionTimeout to 30 sec. ( It was at 0 i.e. 'No limit')

2023-03-08 20:25 UTC, JingleH commented
One thing I would suggest is that if we want to change the html output location, we should also add it to .gitignore

2023-03-08 20:37 UTC, JackySun9 commented on playwright.config.js
> +    : [['html', { outputFolder: 'test-html-results' }]],
can we have both list and html?

2023-03-08 21:44 UTC, skumar09 commented
> One thing I would suggest is that if we want to change the html output location, we should also add it to .gitignore
@JingleH , good point, i have updated the PR, pls review

2023-03-08 21:48 UTC, JackySun9 approved these changes

2023-03-09 18:11 UTC, JingleH approved these changes

2023-03-09 18:13 UTC, JingleH commented on playwright.config.js
> +    : [['html', { outputFolder: 'test-html-results' }]],
seconding this. But I'm also thinking that do people want that generated html by default? It does increases the execution time at the end by quite some lot

2023-03-09 21:12 UTC, amauch-adobe requested changes
Love the idea of adding parallel executions, see my comments below.

2023-03-09 21:12 UTC, amauch-adobe commented on playwright.config.js
> +  workers: process.env.CI ? 2 : undefined,
I'm cool with trying it out and seeing how it fairs over the longterm, as I mentioned I tried it in one PR and kept updating it over the day to see test results.  Longterm might be a good test factor to see if it was just an issue for the time I was doing it.  Let's give it a try, we can always discuss changing it later or something.

2023-03-09 21:12 UTC, amauch-adobe commented on .gitignore
> +/test-html-results/
This entirely depends on if we decide to always print out the HTML report for local runs, see my comment below.  If we are going to then yes let's add this to .gitignore, otherwise all HTML reports will by default go to the playwright-report/ directory that is already in the .gitignore file.

2023-03-09 21:17 UTC, skumar09 commented on playwright.config.js
> +    : [['html', { outputFolder: 'test-html-results' }]],
@amauch-adobe  this html report is only in local laptop/machine run, not in git. this will reduce lot of effort in test debug locally.

2023-03-09 21:17 UTC, amauch-adobe requested changes

2023-03-09 21:17 UTC, amauch-adobe commented on playwright.config.js
>      /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
I saw in a previous commit that the actionTimeout was updated to 300000 milliseconds, did you revert the change?

2023-03-09 21:27 UTC, skumar09 commented on playwright.config.js
>      /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
- yeah , i was thinking failure for FaaS script was due to timeout, but looks their failure was different issue. 
- I will not encourage to have actionTimout set to 0 i.e. no limit.  we should set somewhere between 60 sec to 300 sec.
-

2023-03-09 23:48 UTC, amauch-adobe commented
@skumar09 and I had a quick huddle on my comments to the PR and worked through them. All are approved after we decided to add back the actionTimeout to 30 sec.

2023-03-09 23:48 UTC, amauch-adobe approved these changes
Approved.

2023-03-10 00:19 UTC, merged