DC converter and review block selector updates
adobecom/nala pull request #92
Opened 2023-03-28 23:47 UTC by JFernandezAdobe

2023-03-29 02:12 UTC, skumar09 commented
@JFernandezAdobe: Few tests are failing with WebKit browser, can you please review, [ not sure if it is a known issue or if it expected ]

2023-03-29 18:51 UTC, amauch-adobe requested changes
Does the updated selector variable that looks to be assigned two different selectors (separated by a comma on one line) work?  I would think it would fail since I assume it would expect the comma-delimited second selector to be assigned a different variable.

2023-03-29 18:51 UTC, amauch-adobe commented on selectors/dc/dc_converter.selectors.js
> +  '@convert-button': '[data-test-id="convert"], [data-test-id*=compress-button]',
Does this work with having two different selectors for one variable?  Just curious since they are on the same line but are comma-separated, so I figured it would break.

2023-03-30 18:29 UTC, JFernandezAdobe commented on selectors/dc/dc_converter.selectors.js
> +  '@convert-button': '[data-test-id="convert"], [data-test-id*=compress-button]',
Yes, it works. The tests that use the same selector passed.

2023-03-30 18:46 UTC, amauch-adobe commented on selectors/dc/dc_converter.selectors.js
> +  '@convert-button': '[data-test-id="convert"], [data-test-id*=compress-button]',
sounds good.

2023-03-30 18:50 UTC, amauch-adobe commented
I'm okay approving once all tests pass, it seems like the webkit tests for DC has been difficult to get to pass consistently.  What is your take on it @JFernandezAdobe?

2023-03-31 22:09 UTC, JFernandezAdobe commented
@amauch-adobe @skumar09 I can't reproduce the test issues in Webkit locally. Skipping Webkit for now until there is a solution in place.

2023-04-03 17:16 UTC, amauch-adobe approved these changes
Approved.

2023-04-05 18:42 UTC, chrischrischris approved these changes

2023-04-05 18:45 UTC, skumar09 approved these changes

2023-04-05 18:46 UTC, merged