[MWPW-128064] Header/Footer component checks
adobecom/nala pull request #96
Opened 2023-03-30 20:25 UTC by chadsunvice

* Header/Footer infrastructure
* Header first checks (a lot of the logic is under development on Milo side so these will be updated)

2023-03-30 21:50 UTC, amauch-adobe requested changes
Footer.test.js is an empty file, don't know if it should be committed empty.  I also added the new tag labels you added in the two new spec files and added Nala to run against your PR.

2023-03-30 21:50 UTC, amauch-adobe commented on tests/feds/footer.test.js
Perchance is this supposed to be empty? ;)

2023-03-30 21:50 UTC, amauch-adobe commented on pages/feds.header.page.js
Looks like this file is also in another PR #90, just want to make sure they stay in sync.

2023-03-31 07:23 UTC, chadsunvice commented on pages/feds.header.page.js
I've synced them beforehand to have no issue when merging. I have the latest version into the 3 PRs open.

2023-03-31 07:23 UTC, chadsunvice commented on tests/feds/footer.test.js
I can remove the file for now, I agree. The Footer isn't ready yet and this was a placeholder of sorts.

2023-03-31 17:18 UTC, amauch-adobe approved these changes
Approved.

2023-03-31 18:14 UTC, JackySun9 approved these changes

2023-03-31 18:55 UTC, merged