Include DC pages in columns and feds tests
adobecom/nala pull request #98
Opened 2023-04-04 21:46 UTC by JFernandezAdobe

2023-04-05 16:17 UTC, JFernandezAdobe commented
https://github.com/adobecom/nala/actions/runs/4620467302/jobs/8170610890?pr=98
`Notice:   69 passed (3.1m)`

2023-04-05 18:43 UTC, amauch-adobe requested changes
See my comments on the hlx.live url dc domain change to the failedblock test.

2023-04-05 18:43 UTC, amauch-adobe commented on features/milo/failedblock.spec.js
Are you guys allowing the failedblock code to run on production URLs?  As far as I know, the current code configuration for the FailedBlock is to only show up on hlx.page or hlx.live URLs, this is by design so public consumers won't see the failed block wrapper.  On production, if a failed block is present it will just show up as empty whitespace on the page.  Are you guys doing something special with your setup to allow the failedblock wrapper to show up on production?

2023-04-05 18:43 UTC, amauch-adobe commented on pages/feds.header.page.js
@chadsunvice I think it would be good for you to look over this PR since there are updates being made to the original specs and poms for the feds pages.

2023-04-05 23:23 UTC, JFernandezAdobe commented on features/milo/failedblock.spec.js
> As far as I know, the current code configuration for the FailedBlock is to only show up on hlx.page or hlx.live URLs, this is by design so public consumers won't see the failed block wrapper.

@amauch-adobe I have seen the failed block message before in stage.adobe.com, not only in hlx.page or hlx.live URLs. Please see [MWPW-125609](https://jira.corp.adobe.com/browse/MWPW-125609).

@Blainegunn could you confirm if this is not the case anymore? Should we create a ticket to investigate this?

Also, the reason for not running DC tests in hlx.live and replacing them with prod URLs is same as https://github.com/adobecom/nala/pull/77.

2023-04-06 04:35 UTC, amauch-adobe commented on features/milo/failedblock.spec.js
@JFernandezAdobe I can understand that stage.adobe.com shows it up since you guys are filtering hlx.page to that domain, I just didn't think the failed block would show up for www.adobe.com production URLs since that is public-facing and shouldn't show the wrapper.  I was just saying we needed to pick a URL that would work for the wrapper to show up on.

2023-04-10 20:18 UTC, amauch-adobe commented on features/milo/failedblock.spec.js
@JFernandezAdobe I'm okay with approving this PR, I would like to make sure whether or not the failedblock wrapper shows up on the UI for www.adobe.com URLs since that is production public facing URLs and per the failed block design it shouldn't be able to.  Also, I really would like @chadsunvice to first have a look for the FEDS test side of things as well.

2023-04-10 20:19 UTC, amauch-adobe approved these changes
Approved, pending my question about the failed block wrapper showing up against www.adobe.com and @chadsunvice having a review of the FEDS test side of things.

2023-04-20 16:55 UTC, merged